### ISSUE TITLE
Buggy PV online SF-zh

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#102]
37.Nc1 is not legal after 36...N@a3+
From the position :  https://fr.lichess.org/Z03k47uI#71

Screenshots : 
https://www.dropbox.com/s/dwhwv76xatauhax/Capture%20d%27%C3%A9cran%202016-11-03%2012.59.58.png?dl=0

https://www.dropbox.com/s/3joiostsa5fmwsa/Capture%20d%27%C3%A9cran%202016-11-03%2013.01.13.png?dl=0

**Comment by ddugovic** [comment]
Cannot reproduce in ddugovic/Stockfish.

**Comment by Vinvin20** [comment]
Strange ! Here, I restarted my browser and it happens again.
Firefox, Win7, 32 bits.

**Comment by ddugovic** [comment]
ddugovic/Stockfish does not run in a browser, it runs from a command line.

**Comment by Vinvin20** [comment]
Does that means, I've to post this issue on Lila ?

**Comment by ddugovic** [comment]
I suggest the [Lichess Feedback forum](http://en.lichess.org/forum/lichess-feedback), unless another developer suggests a better place.  This issue tracker is best suited for issues which aren't UI-dependent.

**Comment by niklasf** [comment]
Yes, please post this in lila. And also other issues you find, since chances are it's a bug in the Stockfish integration, not Stockfish itself.
