### ISSUE TITLE
Time forfeit by Stockfish zh 15Nov2016

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#134]
http://www.talkchess.com/forum/viewtopic.php?p=696446#696446

```
[Event "CCVA Stockfish zh 15Nov2016 Gauntlet Blitz Tour Nr 36"]
[Site "i7-2600K"]
[Date "2016.11.27"]
[Round "1"]
[White "Stockfish zh 15Nov2016 64bit"]
[Black "Imortal 2.17 64bit"]
[Result "0-1"]
[PlyCount "58"]
[Termination "time forfeit"]
[TimeControl "180+2"]
[Variant "crazyhouse"]

1. e4 {book} e5 {book} 2. Nf3 {book} Nc6 {book} 3. Bb5 {book} Bc5 {book}
4. Nc3 {book} Nge7 {book} 5. d3 {book} O-O {book} 6. Bc4 {+0.87/18 8.4s}
h6 {-1.78/15 6.5s} 7. Na4 {+1.02/15 2.7s} d6 {-2.18/14 8.8s}
8. h3 {+0.18/19 40s} Be6 {-0.64/14 8.4s} 9. Nxc5 {+0.49/18 2.7s}
dxc5 {+0.48/11 6.0s} 10. Bxe6 {+0.54/16 1.2s} fxe6 {+0.27/11 7.9s}
11. B@g4 {+0.93/17 11s} N@d4 {+0.29/12 7.6s} 12. Nxd4 {+1.16/17 7.8s}
Nxd4 {+0.85/10 7.3s} 13. O-O {+1.30/17 3.0s} B@a4 {-0.21/12 7.1s}
14. b3 {+1.59/17 7.8s} Bxb3 {+1.38/13 6.8s} 15. cxb3 {+0.64/19 12s}
P@e2 {+1.38/12 6.6s} 16. Bxe2 {+1.04/17 2.1s} N@c3 {+0.96/13 6.3s}
17. Bg4 {+1.46/16 2.9s} Nxd1 {+0.49/11 6.1s} 18. Rxd1 {+1.29/15 1.3s}
Rxf2 {+3.81/10 5.6s} 19. Be3 {-2.49/16 26s} P@g3 {+7.29/8 5.7s}
20. Bxf2 {-4.77/17 31s} Q@h2+ {+9.59/10 5.6s} 21. Kf1 {-4.77/1 0s}
gxf2 {+9.59/10 5.4s} 22. N@e2 {-6.70/17 25s} Qf8 {+10.06/9 5.0s}
23. B@f3 {-7.20/14 16s} Nxf3 {+13.45/9 5.0s} 24. Bxe6+ {-8.67/13 4.3s}
Kh8 {+20.25/9 3.9s} 25. R@h7+ {-17.80/14 9.1s} Kxh7 {+23.67/9 4.8s}
26. Bg8+ {-21.13/13 4.9s} Kxg8 {+37.65/8 4.3s} 27. P@h7+ {-25.27/12 2.5s}
Kh8 {+M11/8 4.7s} 28. N@g6+ {-M10/14 2.0s} Nxg6 {+M9/8 4.6s}
29. Kxf2 {-M8/17 2.0s} B@e1+ {+M7/7 4.2s, White loses on time} 0-1
```

**Comment by ddugovic** [comment]
Is this issue reproducible?  If so please provide duplication steps.

**Comment by Vinvin20** [comment]
The method to reproduce is to play many games. 
Here it was after 150 games.

**Comment by ddugovic** [comment]
Incorrect: Stockfish has played [100,000+ games](http://en.lichess.org/games/search?players.a=&players.b=&players.white=&players.black=&players.winner=&ratingMin=&ratingMax=&hasAi=1&aiLevelMin=&aiLevelMax=&source=&perf=&mode=&turnsMin=&turnsMax=&durationMin=&durationMax=&clock.initMin=&clock.initMax=&clock.incMin=&clock.incMax=&status=&winnerColor=&dateMin=1d&dateMax=&sort.field=d&sort.order=desc) in the last 24 hours and never timed out.

**Comment by Vinvin20** [comment]
On lichess, it plays with a fixed time. 
In the game I gave you, the time management from SF-zh was used ...

**Comment by ianfab** [comment]
Stockfish's time management is the same for all variants and standard chess. As far as I know, the time loss issues (e.g. TCEC 8) have not really been solved, but are worked around by a conservative choice of UCI parameter values.

**Comment by Vinvin20** [comment]
And btw, here, SF lost on time when it will be mated in a couple of moves. Not a big deal !
