### ISSUE TITLE
Out-of-bounds array access in function FromToStats::get if game is crazyhouse

### ISSUE THREAD

**Issue by sf-x** [ddugovic/Stockfish#137]
Out-of-bounds array access in function `FromToStats::get` (in `src/movepick.h`) if game is crazyhouse occurs if the second argument to `get` is a drop move (for drop moves `from_sq` returns 64 (~~`MOVE_NONE`~~`SQ_NONE`) which is equal to the respective `FromToStats::table` array dimension.

**Comment by ianfab** [comment]
Thanks for reporting. #138 should fix it.
