### ISSUE TITLE
Crazyhouse: Position::do_move fails to update nonPawnMaterial if the move is a drop

### ISSUE THREAD

**Issue by sf-x** [ddugovic/Stockfish#141]
When playing crazyhouse, `Position::do_move` fails to update `st->nonPawnMaterial` if the move is a drop.
See also: https://github.com/ddugovic/Stockfish/issues/94#issuecomment-258147272

**Comment by sf-x** [comment]
CAUTION: fixing this might hurt strength, as the king safety, PSQT, etc. were tuned with this bug artficially decreasing game phase. Re-tuning after fixing this bug will probably be beneficial.

**Comment by ianfab** [comment]
It is easy to fix this, but I will have to test whether this regresses playing strength.

**Comment by sf-x** [comment]
By how much approximately?

**Comment by ianfab** [comment]
Actually, it turned out to be an improvement and even passed an SPRT test (see #143).
