### ISSUE TITLE
Issues with FICS and crazyhouse

### ISSUE THREAD

**Issue by demts** [ddugovic/Stockfish#151]
I have stockfish - crazyhouse setup on FICS, and while it is playing a great game usually, it regulary freezes, here is one example

 ```
 1.  e4      (0:00.000)      e6      (0:00.000)   
  2.  d4      (0:01.337)      d5      (0:01.314)   
  3.  e5      (0:00.575)      c5      (0:03.633)   
  4.  Nf3     (0:02.469)      Qb6     (0:03.164)   
  5.  dxc5    (0:05.845)      Bxc5    (0:05.173)   
  6.  P@d4    (0:00.905)      Be7     (0:00.013)   
  7.  Be2     (0:02.615)      P@g4    (0:02.640)   
  8.  Ng5     (0:01.807)      h5      (0:04.594)   
  9.  O-O     (0:04.992)      Nc6     (0:01.738)   
10.  Nc3     (0:01.571)      a6      (0:10.755)   
11.  f3      (0:12.332)      Nxd4    (0:01.031)   
12.  Be3     (0:01.270)      Bxg5    (0:10.027)   
13.  Bxd4    (0:01.549)      Be3+    (0:00.472)   
14.  Bxe3    (0:00.929)      Qxe3+   (0:08.599)   
15.  B@f2    (0:00.002)      Qxe5    (0:00.012)   
16.  fxg4    (0:05.221)      hxg4    (0:01.292)   
17.  Bg3     (0:10.756)      B@e3+   (0:01.975)   
18.  P@f2    (0:03.658)      P@f4    (0:02.667)   
19.  N@d3    (0:05.907)      fxg3    (0:01.697)   
20.  Nxe5    (0:03.230)      Bxf2+   (0:00.919)   
21.  Rxf2    (0:00.001)      gxh2+   (0:00.283)   
22.  Kf1     (0:02.653)      h1=Q+   (0:00.609)   
23.  B@g1    (0:00.002)   
```

Here black (stockfish) became unresponsive, and seemed to not have received the move (it kept pondering).

As of now, it only lost one game against a human, but that seemed to be a bug - it allowed a mate in 1.  Here is the game (stockfish white)
```
  1.  e4      (0:00.000)      e5      (0:00.000)   
  2.  Nf3     (0:03.318)      Nc6     (0:00.001)   
  3.  Bc4     (0:02.014)      Be7     (0:00.449)   
  4.  d4      (0:10.357)      exd4    (0:00.953)   
  5.  Nxd4    (0:01.404)      Bf6     (0:00.812)   
  6.  Nxc6    (0:02.905)      bxc6    (0:00.001)   
  7.  P@g5    (0:06.532)      Bxg5    (0:09.320)   
  8.  Bxf7+   (0:01.749)      Kxf7    (0:00.634)   
  9.  Qh5+    (0:00.104)      B@g6    (0:02.059)   
10.  N@e5+   (0:01.429)      Kf8     (0:07.549)   
11.  Qxg6    (0:00.099)      hxg6    (0:02.063)   
12.  Nxg6+   (0:03.190)      Ke8     (0:00.646)   
13.  P@f7+   (0:01.871)      Kxf7    (0:00.577)   
14.  Nxh8+   (0:00.172)      Kf8     (0:03.068)   
15.  B@b4+   (0:08.411)      d6      (0:02.518)   
16.  R@f7+   (0:00.947)      Ke8     (0:01.676)   
17.  Rxg7    (0:03.695)      Be6     (0:06.189)   
18.  P@f7+   (0:01.023)      Bxf7    (0:00.785)   
19.  Nxf7    (0:00.875)      P@e2    (0:10.041)   
20.  Nxd6+   (0:01.429)      Qxd6    (0:06.191)   
21.  P@f7+   (0:01.778)      Kd7     (0:01.136)   
22.  fxg8=Q+ (0:00.099)      N@e7    (0:01.986)   
23.  P@f7    (0:03.065)      Q@d1#   (0:02.177)   
```
      {White checkmated} 0-1

The version that played was compiled today, so latest version.

**Comment by ddugovic** [comment]
Thanks for the report.  What GUI or interface was used such that I may be able to duplicate this?

**Comment by demts** [comment]
I used winboard with the UCI2WB adapter and instructions from this thread
http://talkchess.com/forum/viewtopic.php?t=61959

Here is the command line I used

WinBoard -zp -ics -icshost freechess.org -fcp "stockfish.exe" -fd "C:\Stockfish-master\src" -fUCCI -variant crazyhouse -zippyVariants crazyhouse  -zippyGameEnd='seek zh 1 0 f\n seek zh 2 0 f\n' -icshelper timeseal -firstFeatures {variants="crazyhouse"}

I doubt that the mate in 1 game was caused by the fact that the game was played through winboard.

**Comment by ddugovic** [comment]
Thanks; likely Stockfish did something insane under these conditions and now I understand how to test this such that I may attempt to duplicate & fix it.

I didn't realize UCI2WB supported crazyhouse and I knew that [PolyGlot](http://github.com/ddugovic/polyglot) (in place of UCI2WB) does not support crazyhouse.

**Comment by HGMuller** [comment]
UCI2WB is a 'variant agnostic' adapter, which should automatically support almost any variant that does not use incompatible move or FEN notation between UCI and CECP. When there is an incompatibility in this respect it is aware of (such as the move notation in USI Shogi engines,where moves are written as 6g6f instead of c3c4, it does the conversion. But otherwise it just transforms the syntax of one protocol into that of the other without being aware what the moves mean.

With the latest version, where I packaged WinBoard, UCI2WB and Stockfish-variant, even KOTH and racing Kings seemed to work fine.

**Comment by ddugovic** [comment]
Many thanks @HGMuller ! :-)

By the latest version you're referring to WinBoard 4.8-beta on http://hgm.nubati.net/ , correct?  Several players are asking me where to find such a download.

(Also a player contacted me asking for a 32-bit Windows download!)

**Comment by sf-x** [comment]
http://talkchess.com/forum/viewtopic.php?t=62331

**Comment by demts** [comment]
I updated to the very latest UCI2WB adapter and at least in 10 games the problem didn't occur. But I cannot really test it properly since I do not survive long enough :) If someone could log on onto FICS (with tjchess or so) and play a series of games to test, I'd appreciate it.

**Comment by ddugovic** [comment]
@demts I hope that by "the very latest" you refer to either sf-x instructions or [this comment](http://github.com/ddugovic/Stockfish/issues/147#issuecomment-264663070) which both link to the WinBoard-AA beta release.

**Comment by demts** [comment]
I used winboard 4.8.0b with the "very latest" http://hgm.nubati.net/UCI2WB.exe 
I have not yet tried winboard-AA - but like I said, problem seems to be solved for now - if you like you can always close this issue, and we could reopen it if problems reoccur.
