### ISSUE TITLE
Variant relay exit unexpectedly

### ISSUE THREAD

**Issue by lantonov** [ddugovic/Stockfish#154]
All other variants are working. Relay starts calculating but then suddenly exits.
See the Talkchess topic:
http://talkchess.com/forum/viewtopic.php?t=62331&start=20

**Comment by ddugovic** [comment]
I'm seeing the TalkChess topic and I have no understanding of what you're talking about?

**Comment by lantonov** [comment]
I am talking about the following sequence:
1. Start Winboard
2. Load Stockfish as white and Stockfish as black
3. Choose relay: File --> New variant ... --> relay
4. Start Stockfish vs. Stockfish: Mode --> Two Machines
5. Get the error message:
 "Error: first chess program (UCI2WB debug -normal "Stockfish-windows-amd64.exe" "..\Stockfish") exited unexpectedly"

**Comment by ddugovic** [comment]
Oops.  The [relay variant](http://relaychess.org/) implementation is alpha and I need to disable it.

**Comment by lantonov** [comment]
Thanks, appreciate your efforts. Meanwhile, HGM is making good progress on integrating this variant Stockfish with Winboard / Xboard
