### ISSUE TITLE
More lost from SF-zh Level 8 from Dec 8th 2016

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#164]
"profz" won 2 games, "chickencrossroad" won 5 and "xuanet" won 3.

https://fr.lichess.org/6FyMXy7K
https://fr.lichess.org/1fIzyOeD

https://fr.lichess.org/RxvVnudr
https://fr.lichess.org/wqDXOG7w/black
https://fr.lichess.org/6eT0LC1i
https://fr.lichess.org/dnjeJ9Px/black
https://fr.lichess.org/GLYtDpcc/black

https://fr.lichess.org/QK9J2s97
https://fr.lichess.org/CpgqVXa0
https://fr.lichess.org/UO5fX5YR

**Comment by ddugovic** [comment]
Last release of http://github.com/niklasf/Stockfish was 9 days ago, but after my next improvement (tuning razor_margin) it may be worth manually analyzing these games using the new engine.

**Comment by Vinvin20** [comment]
It's time to release the latest version ! ;-)

**Comment by ianfab** [comment]
[This](https://en.lichess.org/GLYtDpcc/black#32) is an interesting position. For a human player, it is obvious that you have to play N@g3 or at least you must keep a knight in hand to prevent checkmate if you can not checkmate you opponent, whereas Stockfish seemingly pushes the mate beyond its search horizon by a lot of checks and drops its most important piece to give check.

**Comment by Vinvin20** [comment]
> This is an interesting position

BTW, the position is already hopeless. The biggest problem in this game are the pieces not developed on a1-b1-c1.

**Comment by ianfab** [comment]
Yes, but Stockfish has to evaluate the position correctly in order to be able to avoid it.

**Comment by Vinvin20** [comment]
The more I look at all of this games, the more I think the players used engine assistance to beat SF-Level8, sometimes the win is so deep and so complicated ...

**Comment by ianfab** [comment]
I disagree. In some games Stockfish simply blundered or misevaluated the position, and these players are very strong in crazyhouse, so I do not see a reason to be suspicious. Also have a look at how many games they played against Stockfish and lost.

**Comment by Vinvin20** [comment]
Yes, I was probably biased by watching only humans wins.

**Comment by ddugovic** [comment]
> `r1b2k1r/ppp1bNp1/7p/3n4/8/7p/PPP1BPpP/RNB2RK1[NQPPPPq] w - - 32 17` is an interesting position...

Here are the evaluations before and after N@g3:

```
      Eval term |    White    |    Black    |    Total    
                |   MG    EG  |   MG    EG  |   MG    EG  
----------------+-------------+-------------+-------------
       Material |   ---   --- |   ---   --- |  6.28  8.79 
      Imbalance |   ---   --- |   ---   --- |  0.29  0.29 
          Pawns |   ---   --- |   ---   --- | -0.88 -0.89 
        Knights |  0.15  0.02 |  0.08  0.02 |  0.06  0.00 
         Bishop | -0.10 -0.24 | -0.10 -0.34 |  0.00  0.10 
          Rooks |  0.00  0.00 | -0.39  0.00 |  0.39  0.00 
         Queens |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
       Mobility |  0.22  0.35 |  0.38  0.58 | -0.15 -0.23 
    King safety | -5.72 -5.26 | -0.87 -0.63 | -4.85 -4.63 
        Threats |  0.64  0.73 |  1.08  1.34 | -0.44 -0.61 
   Passed pawns |  0.00  0.00 |  0.90 -0.27 | -0.90  0.27 
          Space |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
----------------+-------------+-------------+-------------
          Total |   ---   --- |   ---   --- | -0.22  3.06 

Total Evaluation: 1.51 (white side)

      Eval term |    White    |    Black    |    Total    
                |   MG    EG  |   MG    EG  |   MG    EG  
----------------+-------------+-------------+-------------
       Material |   ---   --- |   ---   --- |  6.02  8.51 
      Imbalance |   ---   --- |   ---   --- |  0.29  0.29 
          Pawns |   ---   --- |   ---   --- | -0.88 -0.89 
        Knights |  0.23  0.04 |  0.08  0.02 |  0.15  0.02 
         Bishop | -0.10 -0.24 | -0.10 -0.34 |  0.00  0.10 
          Rooks |  0.00  0.00 | -0.39  0.00 |  0.39  0.00 
         Queens |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
       Mobility |  0.25  0.37 |  0.38  0.58 | -0.13 -0.21 
    King safety | -2.14 -1.68 | -0.99 -0.87 | -1.15 -0.81 
        Threats |  0.64  0.73 |  1.08  1.34 | -0.44 -0.61 
   Passed pawns |  0.00  0.00 |  0.90 -0.27 | -0.90  0.27 
          Space |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
----------------+-------------+-------------+-------------
          Total |   ---   --- |   ---   --- |  3.34  6.65 

Total Evaluation: 4.28 (white side)
```

I am testing/tuning a new parameter `TempoMg` which may help...

**Comment by ddugovic** [comment]
`TempoMg` and `TempoEg` helped slightly in King of the Hill chess and was free to add for each variant.  I'll tune `TempoMgHouse` and `TempoEgHouse`.

**Comment by ddugovic** [comment]
Tuning reveals that `TempoMgHouse` and `TempoEgHouse` tuned by themselves have little to no effect.

Recently @ianfab tuned crazyhouse parameters.  It should be interesting to see if people observe specific issues in the future!
