### ISSUE TITLE
Man vs machine, the return of the revenge !

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#171]
JannLee lost a match but the fight continues !

The match will be played on Lichess, this Saturday 17th Dec 6pm GMT.
The latest Stockfish will be powered by 6 cores@4GHz.

Time control : 5 min + 15 sec/move.

Join us for live comments on JannLee's Youtube channel : https://www.youtube.com/channel/UCbo8-5AEH7u3lE-yOGeNW1Q

**Comment by Vinvin20** [comment]
Stream here : https://www.youtube.com/watch?v=1huvE4AFM8o

**Comment by Vinvin20** [comment]
The match is delayed by 24 hours because of the "Yearly Crazyhouse Arena".
New schedule : The match will be played on Lichess, this Sunday 18th Dec 6pm GMT.

**Comment by Vinvin20** [comment]
We played only 4 games, JannLee was a bit busy, his wife was not very well.
After this 4 games, I play some games vs eekarf (2764), SF got only black pieces.
SF scored 100% !

You can find the games here : https://fr.lichess.org/@/Vinvin/search?ratingMin=2200&perf=18&sort.field=d&sort.order=desc

**Comment by ddugovic** [comment]
Thanks again to LM JannLee, winner of the [Yearly Crazyhouse Arena](http://www.youtube.com/watch?v=zrOzPvhQizM)!
http://en.lichess.org/kaO5Kgzd
http://en.lichess.org/9LopCxph
http://en.lichess.org/ogcfSTRG
http://en.lichess.org/igEbnBns
