### ISSUE TITLE
Opperwezen accepted to play SF-zh, 6 games match today !

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#176]
Today, Monday 19th.

This evening 19:00 Brussels time (18:00 GMT).
6 games (may be more, if possible), 5m+10s, SF always black.

https://fr.lichess.org/forum/general-chess-discussion/crazyhouse-man-vs-machine-the-return-of-the-revenge-?page=2#17

SF will use SF 6 cores, TC on Winboard side will be set to 3m+6s.

**Comment by ddugovic** [comment]
Well played Opperwezen!
http://en.lichess.org/NYXd1JdO

**Comment by Vinvin20** [comment]
About game 1 : 
SF play Bd6 because it assume that white will play d4.
After e5xd4, the B has a good open diagonal.
So, d4 for white is not good there. So white won't play d4 and Bd6 is bad.

**Comment by Vinvin20** [comment]
6...Bc5 seems bad too because 7.Bg5 is a good move and it forces 7...Be7.
