### ISSUE TITLE
SF-zh matches vs humans

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#178]
JannLee (2805) 1st match : 6-0
JannLee (2805) 2nd match : 4-0
eekarf (2764) : 4-0
mastertan (2688) : 5-0
opperwezen (2687) 5-1! One lost because I let SF play a weak move in the opening : Be6??

note : for the 3 last opponents, SF got only black pieces.

Games are here : 
https://fr.lichess.org/@/Vinvin/search?ratingMin=2100&perf=18&mode=0&sort.field=d&sort.order=desc

It's clear that Stockfish is way stronger than any human in rapid games with good CPU and equivalent time.
JannLee thinks humans would be able adapt to the new engine but I think he's wrong, human cannot catch up, the level of SF is too high for human mind in this very complex game.
On the other side, with 0.5 second (1 CPU), SF stills blunder sometimes some "simple mates" and human can use that to win sometimes. Compare to chess, it's no more possible to tricks SF like that.

This 25 games was a very interesting experience for me !
Any suggestion for further experiences ?

Vincent

**Comment by ianfab** [comment]
Thanks for arranging these matches and summing up the results.

Well, I think you and JannLee are both right. If SF would not be improved for years like it happened for other crazyhouse engines, humans might catch up again, but I do not think this will happen.

Even though opperwezen is very strong, I think there is a typo in his rating ;).

**Comment by Vinvin20** [comment]
> Even though opperwezen is very strong, I think there is a typo in his rating ;).

3687 -> 2687, done ! :-)

**Comment by ddugovic** [comment]
I agree, at present humans still have chances to win!

Even after #131 I think games against "team" opponents (multiple strong players, or a player with engine(s) assistance) could be fun, as could time and/or material odds games!

**Comment by Vinvin20** [comment]
JannLee and opperwezen declined :-(
3 games on going :
https://fr.lichess.org/cp2IRN72609k
https://fr.lichess.org/yxYif0MAy4ey
https://fr.lichess.org/D4YoYzDHmkWx

**Comment by ianfab** [comment]
> 3 games on going

How much time do you use per move for SF's analysis?

**Comment by Vinvin20** [comment]
I've not started the engine yet.
Until January 2nd, I'll be few at home.
I plan to let it run for around 8 hours by move.

**Comment by ianfab** [comment]
Wow, that should yield high-level games. It will be interesting to see whether black can hold.

**Comment by Vinvin20** [comment]
I play only black with SF.

**Comment by ianfab** [comment]
Yes, I know. Considering white's advantage in crazyhouse I think it might be more difficult for SF as black on long time controls.

**Comment by Vinvin20** [comment]
Both games vs mastertan was already >+5 for SF at move 10th.
https://fr.lichess.org/cp2IRN72609k
https://fr.lichess.org/yxYif0MAy4ey

The 3rd game still only on move 3.

**Comment by Vinvin20** [comment]
While playing the 3rd game : https://fr.lichess.org/D4YoYzDHmkWx
Overnight Analyze after : 1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. d3 Nf6 5. O-O O-O 6. Nc3 

```
depth 34 seldepth 51 multipv 1 score cp   0 nodes 5203268910 nps 7959232 time 653740 pv h7h6 c3a4 c5e7 a2a3 d7d6 h2h3 c8e6 c4e6 f7e6 c1e3 d8e8 c2c4 f6h5 a4c3 a7a6 b2b4 h5f4 g1h2 e8f7 e3f4 
depth 34 seldepth 51 multipv 2 score cp -19 nodes 5203268910 nps 7959232 time 653740 pv d7d6 c1g5 h7h6 g5h4 c8g4 h2h3 g4e6 c4e6 f7e6 c3a4 c5b6 a4b6 a7b6 c2c3 d8e8 a2a4 c6e7 b2b4 e7g6 h4g3 
depth 33 seldepth 51 multipv 3 score cp -17 nodes 5203268910 nps 7959232 time 653740 pv a7a5 c1g5 h7h6 g5h4 a5a4 h2h3 c5e7 f1e1 f6h7 h4e7 d8e7 c3d5 e7d8 d1d2 d7d6 b2b4 c6e7 d3d4 e7g6 d4e5 
```

**Comment by Vinvin20** [comment]
The 3rd game will be finished soon too : https://fr.lichess.org/D4YoYzDHmkWx
The tactical shot 11...P@e2!! made the score rise to >+3 quickly.
After forcing 12.Kc1! Q@f1+! score rises to >+8.

Humans are too weak even at corr games :-(

**Comment by ddugovic** [comment]
In fairness to the opponent, 11...P@e2 isn't that surprising, although it's difficult to calculate several moves in advance.

**Comment by Vinvin20** [comment]
P@e2! is not that easy for SF.

BTW, SF entered in the line 5...Bxf2+ to make a forced draw (because score is a slight white advantage after 5.Bg5? ) : 
 5... Bxf2+ 6. Kxf2 Ng4+ 7. Ke1 Qxg5 8. Bxf7+ Kd8 9. Nxg5 P@f2+ 10. Kd2 B@e3+ 11. Kc3 Bxg5 12. Qxg4 N@b5+ 13. Kb3 Nbd4+ 14. Kc3 Nb5+ 15. Kb3 Nbd4+
But eekarf played the incorrect 7.Kf1?

5.Bg5 is a mistake too and 5.Nc3 is way stronger and may be already winning !
See my analyze here : https://fr.lichess.org/forum/game-analysis/crazyhouse-opening-theory?page=4#37

**Comment by ddugovic** [comment]
While I don't yet see a Black advantage after 12. Kc1, it's clear that 12. Kxe2?? gets mated and other moves lose the knight on g5.  I hope it is interesting how this game plays out.

**Comment by Vinvin20** [comment]
A new won game vs eekarf : https://fr.lichess.org/PntdcE8e
Some comments from eekarf  about 10.P@e5?

> i saw the entire sequence that happened in the game, i just didnt think i would be worse, what should i have played
> ah i see now. p@e5 seemed logical to me. its really hard playing the computer. it sees so many moves ahead
