### ISSUE TITLE
Regression test 231216 vs 091216 

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#181]
10s+1s , after 332 games, +54 Elo :
Score of stockfish-modern-091216-1thread vs stockfish-modern-221216-1thread: 133 - 183 - 10 [0.423]
ELO difference: -53.71 +/- 37.67

Now, I start a longer time control : 30s+2s

**Comment by ddugovic** [comment]
==> test20161222-10.out <==
Score of Stockfish 221216 64 BMI2 vs Stockfish 091216 64 BMI2: 255 - 222 - 23  [0.533] 500
Elo difference: 22.96 +/- 29.84
Finished match

==> test20161222-1.out <==
Score of Stockfish 221216 64 BMI2 vs Stockfish 091216 64 BMI2: 279 - 204 - 17  [0.575] 500
Elo difference: 52.51 +/- 30.30
Finished match

==> test20161222-30.out <==
Score of Stockfish 221216 64 BMI2 vs Stockfish 091216 64 BMI2: 271 - 211 - 18  [0.560] 500
Elo difference: 41.89 +/- 30.15
Finished match

==> test20161222-60.out <==
Score of Stockfish 221216 64 BMI2 vs Stockfish 091216 64 BMI2: 98 - 91 - 11  [0.517] 200
Elo difference: 12.17 +/- 47.06
Finished match

**Comment by ddugovic** [comment]
In self-play at 60+10 on Windows, SF does not crash.

**Comment by ddugovic** [comment]
Since tests have been very successful and the deadline is imminent, I updated the #131 submission to 231216 (built 221216).  You're welcome to test although it seems unlikely new results will overturn previous results.

**Comment by Vinvin20** [comment]
+26.35 after 878 games 

> Score of stockfish-modern-091216-1thread vs stockfish-modern-221216-1thread: 382 - 448 - 42 [0.462]
> ELO difference: -26.35 +/- 22.56
> 
> 878 of 1040 games finished.

**Comment by ddugovic** [comment]
Thanks, your result seems to affirm that the `221216` release does not regress! :-)

**Comment by Vinvin20** [comment]
Long TC : TimeControl "3600+60", 81 games.
Games are here : https://www.dropbox.com/s/1pz2l8z678oo84t/Tour-161222-60m-60s.zip?dl=0

Score of stockfish-modern-091216-1thread vs stockfish-modern-221216-1thread: 41 - 32 - 8 [0.556]
ELO difference: 38.76 +/- 73.23
