### ISSUE TITLE
Bullet match video, JannLee vs SF-zh 

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#190]
After 38 lost, JannLee finally won 1 game ! :-)

https://www.youtube.com/watch?v=nXKKPmunAtw&feature=youtu.be&t=1h2m58s

But the infamous 4..Bd6?? Showed again :-( 
here : https://www.youtube.com/watch?v=nXKKPmunAtw&feature=youtu.be&t=15m22s

**Comment by ddugovic** [comment]
How bad is 4... Bd6?

**Comment by Vinvin20** [comment]
Here's the game : https://fr.lichess.org/YOr0b4bA#8
1) it's a move that blocks the d pawn, that prevent the c8 bishop to develop quickly on the c8-h3 diag.
2) SF moves the B again 4 moves later
4.Bd6 loses a tempo, the score on a longer analyses, goes from -1 to -2 with this bad move.

**Comment by ddugovic** [comment]
Good points.  I see that Stockfish (latest master) is no longer interested in this 4... Bd6, though I do not know whether the search heuristic or the evaluation (or both) are to blame for that opening move selection:

```
info depth 1 seldepth 1 multipv 1 score cp -12 nodes 34 nps 17000 tbhits 0 time 2 pv d7d6
info depth 2 seldepth 2 multipv 1 score cp -3 nodes 86 nps 43000 tbhits 0 time 2 pv f8b4 a2a3
```

**Comment by stockfishdeveloper** [comment]
On the whole, it almost looks like ...Bd6 was a hash move--Stockfish moved almost instantly.
