### ISSUE TITLE
Crazyhouse regression test 050117-1t vs-221216-1t

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#205]
Games are here : https://www.dropbox.com/s/x24elrde8au95qr/SF050117-vs-SF091216-30-1.zip?dl=0
TC : 30sec+1sec
Score of stockfish-modern-050117-1t vs stockfish-modern-221216-1t: 550 - 434 - 56 [0.556]
ELO difference: 38.91 +/- 20.66

1040 of 1040 games finished.

**Comment by Vinvin20** [comment]
Congratulations ! +35 Elo in 2 weeks is a nice achievement !

**Comment by ddugovic** [comment]
Cool, it seems the improvement scales.  Does anything remain to be done on #156 ?

**Comment by niklasf** [comment]
Note that 050117 was a pre-release. I intend to include the latest couple of improvements and fixes, maybe even including #207.

**Comment by Vinvin20** [comment]
> Cool, it seems the improvement scales. Does anything remain to be done on #156 ?
It was not an issue but a report of results. Sometimes I use the "issues function" as a forum post.
MP Scaling was very good, no more to say about that ! ;-)

**Comment by ddugovic** [comment]
Copied to https://github.com/ddugovic/Stockfish/wiki/Crazyhouse-regression-test-050117-1t-vs-221216-1t
