### ISSUE TITLE
[test results] SF050117-6t-vs-SF221216-6t-1h-100s

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#214]
Long games (1h+100sec/move) 6 threads, play with HT on a 6x4 GHz  (so about 6x3 GHz per SF instance)

> Score of stockfish-modern-050117-6t vs stockfish-modern-221216-6threads: 12 - 8 - 1 [0.595]
> ELO difference: 67.00 +/- 158.75

Games +eval are here : https://www.dropbox.com/s/e8neis8vvxkdypl/SF050117-6t-vs-SF221216-6t-1h-100s.zip?dl=0

I'll study the eval to try to find some strange things ...

**Comment by ddugovic** [comment]
Thanks, feel free to add test results to the [wiki](http://github.com/ddugovic/Stockfish/wiki).
