### ISSUE TITLE
King exploded too soon

### ISSUE THREAD

**Issue by lantonov** [ddugovic/Stockfish#242]
An atomic game against human in FICS:

[Event "ICS rated atomic match"]
[Site "freechess.org"]
[Date "2017.02.05"]
[Round "-"]
[White "FishTest"]
[Black "fridayknights"]
[Result "0-1"]
[WhiteElo "0"]
[BlackElo "1585"]
[TimeControl "120+10"]
[Variant "atomic"]
[Annotator "1. +0.27"]

1. d4 {+0.27/25 35} Nf6 2. Nf3 {+0.20/26 28} Ne4 3. e3 {+0.52/22 13} Nxf2
{FishTest's king exploded} 0-1

Didn't expect it so soon.

**Comment by ddugovic** [comment]
What user interface... how is this possible?

**Comment by ianfab** [comment]
I think that this was an issue with the communication, so that Stockfish played standard chess. At least I do not have a different explanation for these moves.

**Comment by lantonov** [comment]
The interface is Winboard last version (4.9.1). A second similar game:
[Event "ICS rated atomic match"]
[Site "freechess.org"]
[Date "2017.02.05"]
[Round "-"]
[White "CalicoCat"]
[Black "FishTest"]
[Result "1-0"]
[WhiteElo "1664"]
[BlackElo "1469"]
[TimeControl "120+10"]
[Variant "atomic"]
[Annotator "1... -0.05"]

1. Nf3 d5 {-0.05/22 14} 2. Ne5 Nd7 {+0.26/22 8} 3. Nxd7
{FishTest's king exploded} 1-0

Something is broken, probably GUI. Winboard just recently started to recognise suicide, after I alerted hgm for a problem with book: http://talkchess.com/forum/viewtopic.php?t=62977&postdays=0&postorder=asc&topic_view=&start=10.
HGM mentioned a list of variants but I don't remember if atomic was included or excluded.

**Comment by lantonov** [comment]
Self-play looks OK:
[Event "Computer Chess Game"]
[Site "DESKTOP-RL8DOC5"]
[Date "2017.02.05"]
[Round "-"]
[White "Stockfish 040217 64 BMI2 (UCI2WB)"]
[Black "Stockfish 040217 64 BMI2 (UCI2WB)"]
[Result "1-0"]
[TimeControl "120+10"]
[Variant "atomic"]
[Annotator "1. +2.47   1... -2.33"]

1. Nf3 {+2.47/26} f6 {-2.33/25 42} 2. e3 {+2.27/26 0.3} e6 {-2.06/22 10} 3.
Nd4 {+2.41/25} c6 {-2.37/24 21} 4. Nc3 {+2.09/25 19} Nh6 {-2.42/24 23} 5.
Ndb5 {+2.04/23 17} Bb4 {-2.32/23 2.6} 6. h3 {+2.76/18 6} g6 {-2.12/23} 7.
g3 {+2.46/21 23} a5 {-2.12/23 7} 8. Nc7 {+2.09/22 13} Kf8 {-2.02/25 5} 9.
Nxa8 {+1.87/23} d5 {-2.05/24 46} 10. a3 {+1.77/24 10} e5 {-1.84/23 3} 11.
d4 {+2.11/22 39} exd4 {-1.56/20 15} 12. axb4 {+1.89/23 1.7} Nf5
{-1.58/19 0.1} 13. c4 {+1.63/19 1.7} a4 {-1.60/24 17} 14. Bd3 {+1.75/25} h5
{-1.63/24 9} 15. Bxf5 {+1.63/24} Kg8 {-1.46/24 16} 16. b4 {+1.39/25 1:09}
d4 {-1.14/19 12} 17. e4 {+1.71/23 13} d3 {-1.44/22 10} 18. Qd2 {+1.80/21}
Rh7 {-1.15/20 9} 19. c5 {+1.90/22 24} b6 {-1.07/22 27} 20. O-O {+2.22/25}
bxc5 {-2.09/22 29} 21. b5 {+3.21/21 16} c5 {-3.07/23} 22. b6 {+2.84/20 3}
Bb7 {-3.20/21 1.8} 23. Ba3 {+3.18/21 4} Kh8 {-3.73/23 10} 24. Rfe1
{+3.91/26 0.6} h4 {-4.21/26 29} 25. g4 {+5.06/27 27} c4 26. Qc3
{+5.02/23 2.0} d2 {-4.73/22 7} 27. Red1 {+5.35/25 8} Rd7 28. Bd6
{+6.39/26 20} Qg8 29. g5 {+7.11/23 8} Qd5 {-8.02/24 11} 30. Qxc4
{+7.91/24 0.3} a3 {-9.88/25 37} 31. Bxa3 {+12.54/24 12} Rd8 32. f4
{+12.73/21 3} Kg8 {-12.76/23 7} 33. f5 {+13.65/24 2.1} Kh8 {-16.31/26 28}
34. Kf2 {+22.68/28 9} Rf8 {-20.44/24} 35. Ra5 {+1000.19/30 15} Kg8
{-27.11/27 8} 36. e5 {+1000.14/36 3} Rd8 {-1000.12/39 18} 37. e6
{+1000.12/47 14} Rd4 {-1000.11/51} 38. Ra4 {+1000.11/49 2.8} Rf4
{-1000.10/55 5} 39. Rxf4 {+1000.10/70 7} Kf8 {-1000.09/66} 40. e7
{+1000.09/69 5} Ke8 {-1000.08/79 11} 41. gxf6 {+1000.08/83 1.3} gxf5
{-1000.07/80 1.4} 42. Kg1 {+1000.07/87 1.5} Bh1 {-1000.06/100 8} 43. b7
{+1000.06/127 13} Bxb7 {-1000.05/122 0.1} 44. Kg2 {+1000.05/127 0.6} Kd7
45. e8=Q {+1000.04/127 0.3} Kd6 46. Rb1 {+1000.03/127 0.3} d1=Q 47. Qe6
{+1000.02/127 0.3} Kc5 48. Qd5 {+1000.01/127 0.1}
{mate} 1-0

Probably there are problems with settings file for ICS.

**Comment by lantonov** [comment]
Yes, the problem is with the setting. I didn't pay enough attention to hgm's warning:
"Note that challenges in atomic, crazyhouse etc., allowed by your -zippyVariants, might give you trouble because of the explicit setting of UCI_Variant to suicide. Better let UCI2WB handle this."
Now removing the UCI_Variant part allowed it to play atomic:
[Event "ICS rated atomic match"]
[Site "freechess.org"]
[Date "2017.02.05"]
[Round "-"]
[White "CalicoCat"]
[Black "FishTest"]
[Result "0-1"]
[WhiteElo "1688"]
[BlackElo "1400"]
[TimeControl "120+10"]
[Variant "atomic"]
[Annotator "1... -1.96"]

1. Nf3 f6 {-1.96/24 26} 2. Nc3 Nh6 {-1.14/22 12} 3. Nd5 e6 {+1.34/21 8} 4.
h3 Ng4 {+1.41/22 2.6} 5. hxg4 exd5 {+1.35/23 0.8} 6. e4 d5 {+1.95/20 6} 7.
d4 Na6 {+1.95/23 18} 8. Rxh7 Bg4 {+11.28/21 6} 9. f3 Nb4 {+11.70/21 0.2}
10. Bb5 c6 {+1000.16/21 10} 11. Bf4 dxe4 {+1000.08/49 10} 12. Bc4 Nd5
{+1000.07/59 12} 13. fxg4 Qe7 {+1000.03/86 17} 14. Qe2 Qxe2
{+1000.01/127 0.1}
{CalicoCat's king exploded} 0-1

**Comment by lantonov** [comment]
This issue was of my own making. Closing.
