### ISSUE TITLE
Suicide SF loses deliberately in a drawn position

### ISSUE THREAD

**Issue by lantonov** [ddugovic/Stockfish#268]
In a drawn position, for example 2 opposing kings, SF prefers to lose than shuffle for many moves. For example, the following recent game half an hour ago and one other older game (can't find it in the moment). I am FishTest.

[Event "ICS rated suicide match"]
[Site "freechess.org"]
[Date "2017.03.04"]
[Round "-"]
[White "stayalive"]
[Black "FishTest"]
[Result "1-0"]
[WhiteElo "2764"]
[BlackElo "2976"]
[TimeControl "180"]
[Variant "suicide"]
[Annotator "4... -1.82"]

1. c4 Nh6 2. a4 Nf5 3. g3 Nxg3 4. fxg3 c5 {-1.82/23 7} 5. b4 cxb4 {+0.29/2}
6. Ba3 bxa3 {-0.57/5} 7. Nxa3 b5 {-0.06/33} 8. cxb5 Ba6 {-0.24/36 1.4} 9.
bxa6 Nxa6 {-0.11/32} 10. a5 Qxa5 {+0.00/42} 11. Qa4 Qxd2 {+0.00/43 2.1} 12.
Qxa6 Qxe1 {+0.00/46} 13. Qxa7 Qxa1 {+0.00/54} 14. Qxa8 Qxa3 {+0.00/55} 15.
Qxe8 Qxg3 {+0.00/59} 16. Qxf7 Qxh2 {+0.00/74} 17. Rxh2 g6 {+0.00/74} 18.
Qxe7 Bxe7 {+0.00/85} 19. Rxh7 Rxh7 {+0.00/66} 20. Bh3 Rxh3 {+0.00/81} 21.
Nxh3 Bb4 {+0.00/78 0.7} 22. Nf2 g5 {+0.00/86 2.4} 23. Nd3 d6 {+0.00/76} 24.
Nxb4 d5 {+0.00/78 4} 25. Nxd5 g4 {+0.00/66} 26. Ne3 g3 {+1.35/1} 27. Nf1 g2
{+0.00/3} 28. Nh2 g1=K {+0.00/67 1.7} 29. Nf1 Kxf1 {+2.13/1} 30. e4 Ke2
{+0.00/74 5} 31. e5 Ke1 {+0.00/71 4} 32. e6 Kd1 {+0.00/78 5} 33. e7 Ke2
{+0.00/83 4} 34. e8=K Kf3 {+0.00/127} 35. Kf7 Ke4 {+0.00/127 0.2} 36. Ke8
Kf5 {+0.00/127 0.2} 37. Kd8 Ke4 {+0.00/127} 38. Ke7 Kd3 {+0.00/127 0.2} 39.
Kf6 Kc4 {+0.00/127 0.2} 40. Kg5 Kd5 {+0.00/127 0.2} 41. Kh4 Ke5
{+0.00/127 0.2} 42. Kh3 Kd4 {+0.00/127 0.2} 43. Kg2 Kc5 {+0.00/127 0.2} 44.
Kh3 Kd5 {+0.00/127 0.2} 45. Kg2 Kd4 {+0.00/127 0.2} 46. Kh3 Kc3
{+0.00/127 0.8} 47. Kg2 Kb4 {+0.00/127 1.2} 48. Kh1 Kc3 {+0.00/127 0.2} 49.
Kh2 Kb2 {+0.00/127} 50. Kg1 Kb3 {+0.00/127 0.2} 51. Kf1 Kc3 {+0.00/127 0.2}
52. Kg1 Kd3 {+0.00/127 0.2} 53. Kh1 Ke4 {+0.00/127 0.2} 54. Kg1 Kf4
{+0.00/127 0.2} 55. Kf1 Ke4 {+0.00/127} 56. Ke1 Kd5 {+0.00/127 0.2} 57. Kd1
Kd4 {+0.00/127 0.2} 58. Kc1 Ke4 {+0.00/127 0.2} 59. Kb2 Ke5 {+0.00/127 0.3}
60. Kc1 Ke6 {+0.00/127 0.2} 61. Kb2 Kd5 {+0.00/127 0.2} 62. Kc1 Kc6
{+0.00/127 0.2} 63. Kb2 Kc5 {+0.00/127 0.2} 64. Kc1 Kd4 {+0.00/127 0.2} 65.
Kb1 Ke3 {+0.00/127 0.2} 66. Ka2 Kd2 {+0.00/127} 67. Ka1 Kd3 {+0.00/127} 68.
Ka2 Kd4 {+0.00/127} 69. Kb1 Ke3 {+0.00/127} 70. Ka2 Kd2 {+0.00/127} 71. Ka1
Kd3 {+0.00/127} 72. Ka2 Kd4 {+0.00/127} 73. Kb1 Kd5 {+0.00/127} 74. Ka2 Kd4
{+0.00/127 0.4} 75. Kb1 Kc4 {+0.00/127} 76. Ka1 Kb5 {+0.00/127 0.2} 77. Ka2
Kc6 {+0.00/127} 78. Ka1 Kb5 {+0.00/127 0.4} 79. Ka2 Kc6 {+0.00/127} 80. Ka1
Kb5 {+0.00/127 0.2} 81. Ka2 Kc6 {+0.00/127} 82. Ka1 Kb5 {+0.00/127 0.2} 83.
Ka2 Kc6 {+0.00/127} 84. Ka1 Kb5 {+0.00/127 0.2} 85. Ka2 Ka4 {+0.00/127} 86.
Kb3 Kxb3 {-1000.01/127}
{stayalive wins by losing all material} 1-0

**Comment by ianfab** [comment]
Does the fifty-moves rule not apply in suicide chess? In positions where the game should been drawn due to the fifty-moves rule, SF plays random moves (also for standard chess), because it thinks that all moves are 0.00.

**Comment by lantonov** [comment]
FICS where this played does not apply the 50-move for suicide. Draw should be claimed explicitly and is subject to acceptance by opponent.

**Comment by ianfab** [comment]
Since the UCI protocol does not support draw claims, I do not think there is an easy solution to this problem.

**Comment by lantonov** [comment]
Ok, it's fine me. Should I close this issue ?

**Comment by ianfab** [comment]
Let's wait for @ddugovic's response.

**Comment by ddugovic** [comment]
I agree with @ianfab that since the UCI protocol does not support draw claims, it should be the responsibility of the interface to automatically claim a 50-move draw (irrespective of variant).  If the UCI protocol is to be extended, such a change should be done upstream of this repository.

It seems reasonable to close this issue.
