### ISSUE TITLE
crazyhouse idea: empty 7th/8th rank

### ISSUE THREAD

**Issue by isaacl** [ddugovic/Stockfish#276]
Pawn drops on 7th rank are damaging, perhaps stockfish should include this idea in evals.

**Comment by ianfab** [comment]
As soon as a pawn is dropped on the seventh rank, the passed pawn bonus takes account of it, but I agree that it might help to add an anticipatory malus for holes on the seventh rank, since the pawn drop can also serve as a threat without necessarily being executed.

**Comment by isaacl** [comment]
Right, opening up a hole on the 7th rank is a useful long term positional gain, even if stockfish can't see a direct line with a pawn drop on the square.

**Comment by ddugovic** [comment]
Also queen or rook drops, and sometimes knight drops, tend to be quite strong.

**Comment by isaacl** [comment]
actually drops of any type on any square is usually at least somewhat beneficial :-)

**Comment by ppigazzini** [comment]
The search should already account for:
  - the hole and the pawn drop
  - to drop or to keep in hand (have some pieces in hand is usually somewhat beneficial)

**Comment by ianfab** [comment]
I have started a first test for a very simple implementation of this idea (http://35.161.250.236:6543/tests/view/58c5826a6e23db7956a14344) so that we will have some data as an input for this discussion.

**Comment by ianfab** [comment]
Second try: http://35.161.250.236:6543/tests/view/58e1737d6e23db2fa8080f40. Only add bonus if the pawn can move (advance or capture) from the square on 7th rank.

**Comment by ddugovic** [comment]
I too made an attempt at this idea: http://35.161.250.236:6543/tests/view/58e2ed386e23db2fa8080faa

**Comment by ddugovic** [comment]
Can anyone share a test position where SF misplayed due to not seeing this idea?
