### ISSUE TITLE
Good news in Crazyhouse ! 

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#279]
12-0 for Stockfish Level 8 against #7, time control : 5+0 and 8+0 !
See games here : https://fr.lichess.org/@/opperwezen/search?perf=18&hasAi=1&sort.field=d&sort.order=desc

**Comment by ddugovic** [comment]
AI Level 8 has some wins against GM Seirawan!!
http://en.lichess.org/games/search?players.a=yasser-seirawan&hasAi=1&aiLevelMin=8&sort.field=d&sort.order=desc
