### ISSUE TITLE
optimize=no perft segmentation fault

### ISSUE THREAD

**Issue by ddugovic** [ddugovic/Stockfish#280]
I don't understand how, but sometimes this breaks:

```
$ make clean && make build ARCH=x86-64-bmi2 optimize=no
$ ./stockfish perft
Stockfish 150317 64 BMI2 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott

Position: 1/1
Segmentation fault (core dumped)
```

**Comment by niklasf** [comment]
Can reproduce. It goes away after reverting ab954aec613a8b85029fc270000d045ac5cd459d.

**Comment by ddugovic** [comment]
My machine seemingly randomly reproduces this from every previous commit, but if reverting ab954aec613a8b85029fc270000d045ac5cd459d helps on other people's machines I'll revert it:

```
$ git checkout HEAD~1
$ make clean && make build ARCH=x86-64-bmi2 optimize=no
$ ./stockfish perft
Stockfish 150317 64 BMI2 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott

Position: 1/1
Segmentation fault (core dumped)
```

**Comment by niklasf** [comment]
Sorry, isn't the command supposed to be `perft 1` instead of just `perft`? I might have subconciously done the former when reverting.

**Comment by ddugovic** [comment]
Oops, uci.cpp indicates that perft usage requires supplying a depth.  Thanks for the correction.
