### ISSUE TITLE
Regression in racing kings

### ISSUE THREAD

**Issue by ianfab** [ddugovic/Stockfish#284]
Between the last two releases several improvements for racing kings were commited, but we still get a slight regression: http://35.161.250.236:6543/tests/view/58cf20ac6e23db7956a143c4. I suspect that this was caused by an [upstream change](https://github.com/niklasf/Stockfish/commit/3627348e2b4633604a878b0e5397acb6218a6afc), so I have submitted a test for a reversion of this patch for racing kings: http://35.161.250.236:6543/tests/view/58cfb19e6e23db7956a143c6.

**Comment by ppigazzini** [comment]
General considerations:
1. in the linked regression test a little improvement is between the error bars
2. in the test report is missing a batch of 500 games, I suppose it was purged because too many crashes
3. why so many crashes in the regression tests for all variants? The base was built with the bugged commit on the stack?

**Comment by ddugovic** [comment]
Possibly some crashes or missing data come from my machine which crashed over the weekend.

**Comment by ppigazzini** [comment]
All workers have some crashes. Workers with a high number of cores have a bigger number of crashes, so I presume that the missing data are from my 16 cores worker.

**Comment by ianfab** [comment]
@ppigazzini 
1. According to the test results, the improvements should amount to something like 50 Elo.
2./3. I think that the crashes are caused by the (fixed) issue discussed in #261 and should only occur in the 280217 version. So there should not be any problem with current master.

**Comment by ppigazzini** [comment]
@ianfab 2./3. OK. IMO the regression tests should be performed against a "stable release". At the moment we need the next regression test to be sure to have not introduced a bug
1. OK, but IIRC from Stockfish threads, a ELO gain can be measured only with a fixed games test (as in regression tests), a SPRT test does not give ELO information but only probability wrt ELO gain of passing the test (http://chess-sprt-calc.azurewebsites.net/). Some patches who passed both STC/LTC tests with little games were tested with fixed games to measure the ELO gains (if any).

Anyway finger crossed for your test :)

**Comment by ianfab** [comment]
It is correct that we can not simply apply the Elo formula to SPRT test results, since there is a bias towards the bound that was reached (i.e. positive bias if the test passed, negative if it failed). However, this bias can be accounted for with an adjusted Elo calculation, but it is a bit complicated as far as I know.

The test so far does not show an improvement. The only other upstream change I could imagine to have caused a regression is a [tweak of the threat evaluation](https://github.com/niklasf/Stockfish/commit/8f7e032b8c8c2c19e37ece09eecb589fe2342daa). If neither of these is the cause of the regression, it would probably require a lot of testing to find the regressive patch(es). I am not sure whether it is worth the effort.

**Comment by ddugovic** [comment]
I concur that slight regressions are not a major cause for concern, despite the opinions of one vocal contrarian who frequently comments here...

**Comment by ppigazzini** [comment]
@ianfab bisecting to find a regressive patch never worked in SF.
To test your hypothesis of upstream regressive patches for racing kings, should be useful to measure the ELO gain using the same SF code for base_tag and new_tag (i.e. reverting all upstream's patches of the last month).

**Comment by ianfab** [comment]
@ppigazzini Yes, that is a good idea.
