### ISSUE TITLE
Out-of-bound array access in horde chess and crazyhouse

### ISSUE THREAD

**Issue by ianfab** [ddugovic/Stockfish#287]
Recently, the imbalance calculation has been changed for pawns using an [array of length nine](https://github.com/ddugovic/Stockfish/blob/6f3162abe65e8a77c6f10b3f40486ce900b379a3/src/material.cpp#L281-L283) and it is assumed that there never are more than eight pawns of one color on the board. This does not hold for horde chess and crazyhouse, so we have [out-of-bound accesses](https://github.com/ddugovic/Stockfish/blob/6f3162abe65e8a77c6f10b3f40486ce900b379a3/src/material.cpp#L331). Since this can not be fixed without a functional change, a fix should perhaps be tested with simplification bounds [-10,5] for horde chess and crazyhouse.

**Comment by ddugovic** [comment]
I agree, either I should revert that upstream patch or a fix with those bounds should be applied.

I wonder if [this formula](https://github.com/official-stockfish/Stockfish/pull/1030#issuecomment-285953814) can be extended to 56 pawns...

**Comment by ddugovic** [comment]
I think that patch should fix it... given that it has no functional change versus master and negligible performance impact, maybe I should PR it upstream?

**Comment by ppigazzini** [comment]
Trivial reason: it add characters and not solve any problem for official-stockfish.
What are the others reasons?
