### ISSUE TITLE
Buggy results on the testing platform ?

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#289]
Very random results for this 2 results for the same patch : 
http://35.161.250.236:6543/tests/view/58d1298e6e23db7956a143ed
http://35.161.250.236:6543/tests/view/58d1387d6e23db7956a143f5

"W: 124 L: 21 D: 2" vs "W: 790 L: 767 D: 81"
85% vs 51%

**Comment by ddugovic** [comment]
The results "W: 124 L: 21 D: 2" were produced almost entirely by machine "ctoks-3cores-86".

The other results use a variety of machines.

I would hesitate here before screaming "bug".

**Comment by ianfab** [comment]
The results of a machine with a score of about 50% were purged in the SPRT test. That is why I added the test with a fixed number of games.

The patch in this test changes search reductions for crazyhouse, which might significantly change the search tree, so this could maybe lead to strange effects. LTC failed anyway.

**Comment by ddugovic** [comment]
Out of curiosity... I think some tests are done using `make build` instead of `make profile-build`, no?  (Perhaps I am simply confused.)

For changes which might significantly change the search tree, using `make profile-build` seems important.  (For SPSA tuning, `make build` is probably good enough.)

**Comment by ppigazzini** [comment]
@ddugovic I set on my workers a custom_make.txt with `make profile-build` and `ARCH=x86-64-bmi2` or `ARCH=x86-64-modern` according the architecture

**Comment by MichaelB7** [comment]
I always use profile builds for testing , but fishtest uses make builds.

**Comment by ppigazzini** [comment]
I think that both official and multiversions fishtest use make profile-build

https://github.com/ianfab/fishtest/blob/master/worker/games.py#L47

https://github.com/glinscott/fishtest/blob/master/worker/games.py#L46

**Comment by ddugovic** [comment]
OK, I understand and it seems the initially reported issue is not reproducible.
