### ISSUE TITLE
Time losses in Crazyhouse

### ISSUE THREAD

**Issue by ppigazzini** [ddugovic/Stockfish#290]
There are many time losses in Crazyhouse tests (noise for the statistical framework), I suppose that the mean length of a Crazyhouse game is bigger respect to others variants, and SF keep playing on increment.

BTW the time management can be improved for Crazyhouse.

The time losses problem in TCEC was solved setting the UCI parameters Move Overhead=1000, I'm wondering if this is applicable in fishtest for Crazyhouse.

The hard solution is to use in fishtest only physical workers (no cloud instances) and without any other load on the CPU (my physical worker has fewer time losses than my cloud workers).

These are tests with 500 bench repetitions for each concurrency value, view stdev/mean as noise indicator

```
core i7 3770k (4 cores + HT)
concurrency = 1	mean = 2507653	mean/mean1 = 1.000	stdev =   6302	stdev/mean = 0.00251
concurrency = 2	mean = 2513069	mean/mean1 = 1.002	stdev =   2308	stdev/mean = 0.00092
concurrency = 3	mean = 2487114	mean/mean1 = 0.992	stdev =   3249	stdev/mean = 0.00131
concurrency = 4	mean = 2463138	mean/mean1 = 0.982	stdev =  14272	stdev/mean = 0.00579
concurrency = 5	mean = 2292671	mean/mean1 = 0.914	stdev = 109504	stdev/mean = 0.04776
concurrency = 6	mean = 1793011	mean/mean1 = 0.715	stdev = 154047	stdev/mean = 0.08592
concurrency = 7	mean = 1692038	mean/mean1 = 0.675	stdev =  86287	stdev/mean = 0.05100
concurrency = 8	mean = 1682409	mean/mean1 = 0.671	stdev = 132883	stdev/mean = 0.07898
concurrency = 9	mean = 1464548	mean/mean1 = 0.584	stdev =   8304	stdev/mean = 0.00567
```

```
Azure f16 (16 cores)
concurrency =  1	mean = 2154017	mean/mean1 = 1.000	stdev =  62337	stdev/mean = 0.02894
concurrency =  2	mean = 2206585	mean/mean1 = 1.024	stdev =  42229	stdev/mean = 0.01914
concurrency =  3	mean = 2143828	mean/mean1 = 0.995	stdev =  72040	stdev/mean = 0.03360
concurrency =  4	mean = 2156807	mean/mean1 = 1.001	stdev =  47735	stdev/mean = 0.02213
concurrency =  5	mean = 2063183	mean/mean1 = 0.958	stdev =  87900	stdev/mean = 0.04260
concurrency =  6	mean = 2039584	mean/mean1 = 0.947	stdev =  52266	stdev/mean = 0.02563
concurrency =  7	mean = 1999471	mean/mean1 = 0.928	stdev =  58887	stdev/mean = 0.02945
concurrency =  8	mean = 1968488	mean/mean1 = 0.914	stdev =  51134	stdev/mean = 0.02598
concurrency =  9	mean = 1938773	mean/mean1 = 0.900	stdev =  41271	stdev/mean = 0.02129
concurrency = 10	mean = 1932428	mean/mean1 = 0.897	stdev =  29413	stdev/mean = 0.01522
concurrency = 11	mean = 1923515	mean/mean1 = 0.893	stdev =  36062	stdev/mean = 0.01875
concurrency = 12	mean = 1919080	mean/mean1 = 0.891	stdev =  34468	stdev/mean = 0.01796
concurrency = 13	mean = 1914475	mean/mean1 = 0.889	stdev =  33757	stdev/mean = 0.01763
concurrency = 14	mean = 1914299	mean/mean1 = 0.889	stdev =  34246	stdev/mean = 0.01789
concurrency = 15	mean = 1915141	mean/mean1 = 0.889	stdev =  32124	stdev/mean = 0.01677
concurrency = 16	mean = 1926790	mean/mean1 = 0.895	stdev =  20395	stdev/mean = 0.01058
concurrency = 17	mean = 1868322	mean/mean1 = 0.867	stdev = 160924	stdev/mean = 0.08613
```

```
AWS c4.8xlarge (18 cores)
concurrency =  1	mean = 2531322	mean/mean1 = 1.000	stdev =  11478	stdev/mean = 0.00453
concurrency =  2	mean = 2536413	mean/mean1 = 1.002	stdev =  10937	stdev/mean = 0.00431
concurrency =  3	mean = 2467751	mean/mean1 = 0.975	stdev =  86656	stdev/mean = 0.03512
concurrency =  4	mean = 2417656	mean/mean1 = 0.955	stdev =  10364	stdev/mean = 0.00429
concurrency =  5	mean = 2392274	mean/mean1 = 0.945	stdev =  50759	stdev/mean = 0.02122
concurrency =  6	mean = 2375092	mean/mean1 = 0.938	stdev =  11178	stdev/mean = 0.00471
concurrency =  7	mean = 2363400	mean/mean1 = 0.934	stdev =  29760	stdev/mean = 0.01259
concurrency =  8	mean = 2360889	mean/mean1 = 0.933	stdev =  16626	stdev/mean = 0.00704
concurrency =  9	mean = 2329363	mean/mean1 = 0.920	stdev =  41082	stdev/mean = 0.01764
concurrency = 10	mean = 2355671	mean/mean1 = 0.931	stdev =  10883	stdev/mean = 0.00462
concurrency = 11	mean = 2307269	mean/mean1 = 0.911	stdev =  46616	stdev/mean = 0.02020
concurrency = 12	mean = 2342478	mean/mean1 = 0.925	stdev =  12637	stdev/mean = 0.00539
concurrency = 13	mean = 2296994	mean/mean1 = 0.907	stdev =  48451	stdev/mean = 0.02109
concurrency = 14	mean = 2332714	mean/mean1 = 0.922	stdev =  21208	stdev/mean = 0.00909
concurrency = 15	mean = 2226036	mean/mean1 = 0.879	stdev =  50673	stdev/mean = 0.02276
concurrency = 16	mean = 2236721	mean/mean1 = 0.884	stdev =  29464	stdev/mean = 0.01317
concurrency = 17	mean = 2243075	mean/mean1 = 0.886	stdev =  31232	stdev/mean = 0.01392
concurrency = 18	mean = 2323496	mean/mean1 = 0.918	stdev =   6934	stdev/mean = 0.00298
concurrency = 19	mean = 2121564	mean/mean1 = 0.838	stdev = 186132	stdev/mean = 0.08773
```

**Comment by ddugovic** [comment]
Good question.  For [official competitions](http://ccva.challonge.com/1st_ccva_comp_champ_2016) I have recommended use of `Move Overhead=1000`.

Maybe the time management function can be changed for crazyhouse to double the estimated game length.

**Comment by ianfab** [comment]
Both ideas, tweaking move overhead and improving time management, sound interesting. For now, I submitted a [test with increased move overhead](http://35.161.250.236:6543/tests/view/58d3b19b6e23db7956a14420) to see whether it fixes the issue. 

To adjust time management for variants, we need to either pass the variant (or the position object) to the time management, or get it from the UCI options. The latter might be more convenient, since time management already accesses other UCI option values.

**Comment by ianfab** [comment]
The test was successful, at least regarding the time losses. There was no time loss in more than 1000 games of a variety of machines.

The question now is, how to implement this. Should we only use increased move overhead for crazyhouse or for all variants? I suggest to do the latter, since it also fixes the issue for subvariants like loop chess, and we do not have to check for something like `variant == 'crazyhouse'` in the code.

The second question is whether it should be done implicitly or whether it should be added to the new and base options (i.e. Hash=4 Move Overhead=100).

**Comment by ppigazzini** [comment]
IMO
1. use the solution for all variants
2. explicit: fishtest need to be able to run tests with fixed time (no increment and no Overhead) for patches regarding the time management
3. if the Crazyhouse games run so long perhaps there is an ELO gain in tweaking the time management (e.g. saving more time for the endgame)

**Comment by ianfab** [comment]
When submitting new tests it will now by default insert `Move Overhead=100` in the `Base options` and `Test options` boxes, so these options can be changed if necessary. This is only a [minor code change in fishtest](https://github.com/ianfab/fishtest/commit/34f1bdfe74a9997511a3e7c93933d1d766230c6e) and does not require any updates on the worker side. So I think this can be closed.
