### ISSUE TITLE
Racing kings draw condition

### ISSUE THREAD

**Issue by niklasf** [ddugovic/Stockfish#297]
Stockfish incorrectly believes the position is mate in 1 and throws away the win. I believe racing kings draws were working in an earlier version.

```
Stockfish 280317 64 BMI2 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
setoption name uci_variant value racingkings
position fen 8/k5K1/1r4Q1/2n2R2/8/8/6B1/8 w - - 4 16
d 

 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 | k |   |   |   |   |   | K |   |
 +---+---+---+---+---+---+---+---+
 |   | r |   |   |   |   | Q |   |
 +---+---+---+---+---+---+---+---+
 |   |   | n |   |   | R |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   | B |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+

Fen: 8/k5K1/1r4Q1/2n2R2/8/8/6B1/8 w - - 4 16
Key: 3CA87CC09922DEF8
Checkers: 
go depth 20
[...]
info depth 20 seldepth 2 multipv 1 score mate 1 nodes 742 nps 742000 tbhits 0 time 1 pv g7g8
bestmove g7g8
```

First seen here https://lichess.org/forum/lichess-feedback/racing-kings-ai.

**Comment by niklasf** [comment]
git bisect blames ab954aec613a8b85029fc270000d045ac5cd459d as the first bad commit.

**Comment by ianfab** [comment]
```
setoption name uci_variant value racingkings
position fen 8/k5K1/1r4Q1/2n2R2/8/8/6B1/8 w - - 4 16 moves g7g8
perft 1
```
does not return any moves. I think that this is caused by the early return in the generation of check evasions introduced in https://github.com/ddugovic/Stockfish/commit/ab954aec613a8b85029fc270000d045ac5cd459d. King advances to the 8th rank are handled as checks, so there are "evasions" in racing kings. Removing this early return should fix the issue.

**Comment by niklasf** [comment]
Oh, thanks. I read the diff several times thinking that the early return was sound. @ddugovic: Perhaps we should add this position (or another near-end racing kings position) to the bench suite.

**Comment by ianfab** [comment]
This issue shows that our definition of checks in racing kings can be misleading, so I have submitted a [test for a simplification](http://35.161.250.236:6543/tests/view/58dad1586e23db2fa8080e5c).

**Comment by ddugovic** [comment]
Thanks.  In hindsight that simplification makes great sense and as of [this test](http://35.161.250.236:6543/tests/view/58da3f716e23db2fa8080e45) we know that handling a "king promotion" like a check does not improve performance.

**Comment by ianfab** [comment]
According to the test result it seems to have an effect in qsearch, probably because it helps to correctly evaluate close-to-final positions more quickly. However, we should be able to achieve the same effect in other ways, so an improved version of the simplification might pass.

**Comment by ddugovic** [comment]
True, however owing to #278 simplifications which speed up normal chess are a good thing (even at some expense to variant performance).  In hindsight performance matters most for the most popular variants:
* normal
* crazyhouse

**Comment by ianfab** [comment]
#304 is a Elo-neutral simplification to restore the definition of checks so that checks and evasions are not possible for racing kings.
