### ISSUE TITLE
Atomic variant regression

### ISSUE THREAD

**Issue by ianfab** [ddugovic/Stockfish#31]
I have just found a big regression (>150 Elo) probably caused by the latest merge of upstream commits. There does not seem to be a regression for other variants than atomic chess.

I assume that it is caused by [changes to SEE pruning](https://github.com/ddugovic/Stockfish/commit/714329dbdc3c32af6e899c85409935dc3b6d799c).

Early test results indicate that my assumption is correct. I will do some more testing to find out how to solve the problem and whether it also applies to other variants.

**Comment by ianfab** [comment]
Tests finished:
- no indication of a regression in other variants
- not to use SEE pruning in atomic chess seems to be even better than reverting to the old version: Total: 300 W: 158 L: 94 D: 48 ELO: 75.28 +-36.8 (95%) LOS: 100.0%
- performance of the former against current master: Total: 1000 W: 783 L: 125 D: 92 ELO: 274.22 +-26.3 (95%) LOS: 100.0%

**Comment by ddugovic** [comment]
Interesting!  Given the dynamic nature of atomic chess, aggressive SEE pruning seems unwise.

(There may be a safe way to reintroduce SEE pruning in the future, but such a task seems nontrivial.)

**Comment by ianfab** [comment]
Yes, your explanation sounds logical. I assumed that (to some extent) this should also apply to Racing Kings, so I extended the regression test and indeed there was a regression which was to small to be found given the limited number of games I had used before. The result of the new test is: Total: 1000 W: 333 L: 426 D: 241 ELO: -32.41 +-18.8 (95%) LOS: 0.0%
