### ISSUE TITLE
empty in hand actually checks if hand has 2+ pieces 

### ISSUE THREAD

**Issue by isaacl** [ddugovic/Stockfish#318]
i.e. `pos.count_in_hand<ALL_PIECES>(WHITE) > 1`

Easy to fix but will require retuning, etc.

**Comment by ianfab** [comment]
I can not find this in the code of current master. Are you referring to [`material.cpp`](https://github.com/ddugovic/Stockfish/blob/16d408da0a91e7d0a36f09b2a5d4e5c293e9b3f8/src/material.cpp#L539-L543)?

**Comment by isaacl** [comment]
Ah it was fixed last week in 7815f267.  I was in an old branch.
