### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ppigazzini** [ddugovic/Stockfish#332]
## Wiki
- [x] [home page](https://github.com/ddugovic/Stockfish/wiki)
  - [x] introduction
  - [x] lichess references
  - [x] short instructions to developer
  - [x] short instructions to CPU donors
  - [x] workflow and logic
  - [x] Official SF vs Multi Variant SF
- [x] [developer instructions](https://github.com/ddugovic/Stockfish/wiki/Creating-my-first-test)
  - [x] review the rules and clean up
- [x] worker installation on [Windows](https://github.com/ddugovic/Stockfish/wiki/Running-the-worker-on-Windows)
- [x] worker installation on [Linux](https://github.com/ddugovic/Stockfish/wiki/Running-the-worker-on-Linux)
- [x] worker installation on Cloud
- [x] [fishtest server installation on Ubuntu](https://github.com/ddugovic/Stockfish/wiki/Installing-a-development-multi-variant-fishtest-server-on-Ubuntu)
  - [x] systemd unit
  - [x] tests on older Ubuntus
- [x] [cutechess-cli QT static](https://github.com/ddugovic/Stockfish/wiki/How-To-build-cutechess-with-QT-5-static)
- [ ] clean up the Pages Summary: organize some old pages: e.g. [this](https://github.com/ddugovic/Stockfish/wiki/Crazyhouse-regression-test-050117-1t-vs-221216-1t)

## MV Stockfish
- [x] update Readme.md
  - [x] introduce Multi Variant Stockfish
- [x] update AUTHORS

## MV Fishtest
- [x] update Readme.md
  - [x] introduce Multi Variant Fishtest
  - [x] update/delete very old information
- [x] update AUTHORS
- [x] server setup file
  - [x] instructions to install on Ubuntu
  - [x] use systemd to auto start the startup script
- [x] worker setup files
  - [x] Linux worker
  - [x] Windows worker

**Comment by ddugovic** [comment]
One thing I don't understand is why upstream provides an AUTHORS file given the difficulty of maintaining the list versus the ease of viewing the [contributor list](http://github.com/ddugovic/Stockfish/graphs/contributors) and seeing who contributed what.

**Comment by ppigazzini** [comment]
@ddugovic IMO code licensing must be crystal clear also without an online connection:
  - the last section of the GPL suggests to write the authors name in the code
  - with many contributors this is not a practical approach, so view [this stackoverflow suggestion](http://stackoverflow.com/questions/11670368/gpl-copyright-notice-when-contributing-new-files): 
"In a central approach an accepted procedure is to have a so called AUTHORS (and probably additionally a CONTRIBUTORS) file listing the authors of the software and to have a COPYING file that contains the license."

Anyway licensing is not a simple and funny matter, so an easy way it to copy from a reliable source of information (e.g. a more structured project)

Regarding MV Stockfish:
  - IMO you and Fabian should decide how to deal with the licensing
  - the AUTHORS first line report the git command to generate the contributors list, it's an easy work
  - copyright info in .h .cpp files (adding your names?)
