### ISSUE TITLE
How to play variant in UCI?

### ISSUE THREAD

**Issue by student-t** [ddugovic/Stockfish#342]
I've made a compile but unsure how to play a variant game in UCI. Should I start off by issuing UCI_Variant? How to make drop a piece on the board in UCI?

Do you have a crazyhouse log from Stockfish that lists the commands you give to the engine?

**Comment by ddugovic** [comment]
I don't expect this answer to become dated, but in case it does, reference implementations may be found at:
http://github.com/niklasf/python-chess
http://github.com/cutechess/cutechess
http://github.com/ianfab/fishtest

I would suggest issuing `setoption name UCI_Variant ...` to inform the engine that a variant is being played; then `position ...` with the FEN and optional move list as per the UCI spec.  Finally, issue the `go` command with parameters of your selection as per the UCI spec.

Offhand I don't recall the exact notation for crazyhouse drops; try `go infinite` to see examples, in case someday that notation changes (in particular pawn drops).

**Comment by student-t** [comment]
Thanks,

setoption name UCI_Variant value crazyhouse
position startpos moves e2e4 f7f5 e4f5 e7e6 f5e6 d8h4 a2a4 h4h2 h1h2 a7a6
go movetime 5000

give:

bestmove Q@f7 ponder e8d8
