### ISSUE TITLE
Regression in Losers Chess

### ISSUE THREAD

**Issue by alwey** [ddugovic/Stockfish#345]
It might be difficult to integrate Losers as a subvariant of LosingChess/Antichess.
Losers has a royal King. There is check and mate. The other variants of Antichess have King(s) that are normal pieces.

commit 88814bd is regressive against 8b052ab:
`Score of SF-88814bd vs SF-8b052ab: 1 - 127 - 0  [0.008] 128`

commit c296c16 does not fully compensate the lost strength:
`Score of SF-c296c16 vs SF-8b052ab: 93 - 192 - 15  [0.335] 300`

Time control: 10s+0.1s/move (100ms Move Overhead)

**Comment by ddugovic** [comment]
I'll examine how much of that 150 Elo we can regain without re-adding 140 lines of code.  The search heuristic and material values are similar, however legal move generation greatly differs.

In practice checkmate is uncommon; the main difference has to do with move generation as it is not possible to sacrifice a king.

**Comment by ianfab** [comment]
I am still convinced that the workflow should be
1. write/modify a patch
2. test. If failing, go back to step 1
3. passed -> merge

not

1. write/modify a patch
2. merge
3. test. If failing, go back to step 1

**Comment by ddugovic** [comment]
Fine.  I'll follow that workflow and stop merging upstream changes as the complexity of this project has gotten out of hand.

**Comment by ianfab** [comment]
Sorry, I did not mean to attack you, I just wanted to express my opinion on testing changes for variants. The topic of upstream changes has repeatedly been discussed here, so I think that my opinion on that should be clear, and as far as I remember there has been a consensus regarding that.

**Comment by ddugovic** [comment]
That's OK, it's a good opinion and while I don't disagree that getting code to **_compile_** post-merge typically isn't complicated by having a large codebase, what happens next (adding code patches to regain Elo) builds technical debt based upon how many patches are added.

I have closed #278 since even `callgrind` fails to convincingly indicate areas for optimization, and we lack policies for improving standard chess performance.

**Comment by alwey** [comment]
@ddugovic  @ianfab : Judging the progress of this project it appears to me that both of you have made good decisions. It is impossible to be right every time.

**Comment by ppigazzini** [comment]
Our resources (CPU, time, developers) are ATM very limited, so compromises are necessary.
Simple curiosity: why a single branch/engine (with many IF) and not a branch/engine for each variant (or variant family)?

**Comment by ppigazzini** [comment]
@ddugovic @ianfab I fixed a stupid mistake in [bench_parallel.sh](https://gist.github.com/ppigazzini/bbbb90fec386c16a13174b1cc20a44d9#file-bench-parallel-sh), a missing a sqrt in error bars computation.
Wiki already fixed.

**Comment by ddugovic** [comment]
@ppigazzini Interesting question... Lichess is the largest benefactor of the engine, and they prefer a single build.  Last I measured using GCC 6 there is a 10% slowdown in standard chess as compared to @official-stockfish (upstream).

The recent change reduces the number of `if` statements (after link-time optimization) encountered while playing most variants; nested if statements only complicate giveaway/suicide/losers variants.

**Comment by alwey** [comment]
@ddugovic @ppigazzini: I would rather have a single engine, at least a single code base. Users may compile or request compiles of specialised engines if they wish.

**Comment by ppigazzini** [comment]
I'm thinking about code management, perhaps with different branches we could have different policies for upstream merge.

**Comment by ddugovic** [comment]
@ppigazzini Certainly this project is open source; I don't see an efficient way to manage two branches but enthusiasts are more than welcome to fork this repository and maintain as many branches as they wish!  `git rebase` and `git cherry-pick` may be useful for such a purpose...

**Comment by alwey** [comment]
Tried my luck and restored old losers specific values for material / imbalance.
#346 

The test results at 10+0.1 are quite agreeable.

**Comment by ppigazzini** [comment]
@alwey are you testing locally or in fishtest?

**Comment by alwey** [comment]
@ppigazzini : Locally. I do not have an account at fishtest for variants yet.

**Comment by ppigazzini** [comment]
@alwey [self registration](http://35.161.250.236:6543/signup) for multi variant fishtest.
Read the [wiki](https://github.com/ddugovic/Stockfish/wiki) for instruction on submitting the test.

**Comment by alwey** [comment]
@ppigazzini : Thank you. I just registered :-) .

**Comment by ppigazzini** [comment]
@alwey perfect. Submit your tests, @ianfab, after a review of the code, will approve the tests. Good luck :)

**Comment by alwey** [comment]
@ppigazzini @ianfab : I think I jjust found a weakness in fishtest: Signatures are tested for standard chess instead of the test's actual variant.

**Comment by ppigazzini** [comment]
@alwey to fix the inconsistency we should do:
1. add some test positions for each variant
2. write a SF patch to deal with bench variant dependent
3. write a fishtest server patch to deal with bench variant dependent
In fishtest worker code the bench it's used to normalize the time control, a patch to deal with bench variant dependent should be not strictly necessary

**Comment by alwey** [comment]
@ppigazzini : I believe the first two items already are present in Stockfish (using UCI commands). But the fishtest worker and server will have to be adapted.

**Comment by ddugovic** [comment]
OK, so I reviewed the code & while on its own it looks reasonable, right now there's a bug which affects `bench all` which I need to fix.

**Comment by ddugovic** [comment]
The bug is localized to horde chess.  Still I'd prefer to first proceed with the simple 220e62c if that's OK.

**Comment by alwey** [comment]
No problem. I think our patches will be quite orthogonal, so I will not resubmit my test (@fishtest) and my pull request. Would that be OK?

**Comment by ddugovic** [comment]
Would it be OK if (supposing my simple patch passes) I take care of rebasing your patch & resubmitting your test?

**Comment by alwey** [comment]
Great, then I will delete my test and get out of the way.

**Comment by ddugovic** [comment]
Thanks and sorry for the inconvenience.  I've traced my remaining bug(s) down to:

```
setoption name UCI_Variant value horde
position fen pppppppp/pppppppp/pppppppp/pppppppp/1pp2pp1/8/PPPPPPPP/RNBQKBNR w KQ - 0 1
go nodes 100
```

which produces differing results with/without `debug=yes`.

**Comment by ianfab** [comment]
@alwey Thanks for creating your first test. You are welcome to use fishtest instead of your local resources if you want to test patches for variants.

> I think I just found a weakness in fishtest: Signatures are tested for standard chess instead of the test's actual variant.

Yes, I thought about that when I started to adjust fishtest for variants, but was unsure whether that should be changed. The main problem is that we would not be able to test versions before the [bench command for variants was introduced](https://github.com/ddugovic/Stockfish/commit/0a444f69a6849d4efc7c29510e362df7a38de187) if we used the variant bench results (same if we used `bench all`, which was introduced even later), or at least it would require some hacks to make it possible. Furthermore, it is quite a useful check to see that standard chess functionality does not change by a patch. I am still torn between the two possibilites, because both have their advantages and drawbacks.

@ddugovic The horde bug should not affect losers chess, and your losers chess test seems to be a normal try for an improvement, so I do not see a reason to keep @alwey from testing his idea unless there is a serious bug in losers chess.

**Comment by alwey** [comment]
@ianfab : 

> Thanks for creating your first test. You are welcome to use fishtest instead of your local resources if you want to test patches for variants.

thank you. Perhaps I can come up with an idea from time to time. 

> Yes, I thought about that when I started to adjust fishtest for variants, but was unsure whether that should be changed. The main problem is that we would not be able to test versions before the bench command for variants was introduced 

I now realise that you had no choice other than to use standard chess benchmarks.

**Comment by ddugovic** [comment]
@ianfab Sorry, I wasn't thinking clearly yesterday regarding:

> @ddugovic The horde bug should not affect losers chess, and your losers chess test seems to be a normal try for an improvement, so I do not see a reason to keep @alwey from testing his idea unless there is a serious bug in losers chess.

There are two things to consider:

1. Some of simple 220e62cc270f2cb18857bcd50d8cf915a66f2601 likely regains Elo.  I say "simple" because it only adds code inside branches already skipped by standard chess, and because most of it is a true simplification for losers chess (reducing number of loops taken).  I'll break it into smaller patches and resubmit for testing...
2. Although the horde bug is severe, it shouldn't affect losers chess; I confused myself while writing yesterday.

**Comment by ppigazzini** [comment]
@ianfab @alwey @ddugovic I opened an [Issue](https://github.com/ddugovic/Stockfish/issues/347) for the signature to keep simple this issue

**Comment by ianfab** [comment]
From @alwey's tests, it looks like reintroducing the quadratic bonuses regains almost all the Elo lost by making losers chess a subvariant. I have started a [test](http://35.161.250.236:6543/tests/view/591ee5be6e23db7f3bc38d6e) to check that.

**Comment by ddugovic** [comment]
Since @alwey 's were very successful, I have merged his changes.

Still don't understand why this is not passing (yet) - is somehow this change functional?
http://35.161.250.236:6543/tests/view/591ecd8b6e23db7f3bc38d63

**Comment by alwey** [comment]
@ianfab : The quadratic bonus patch patch seems to regain much of the old strength but there is still some desire for improvement - as your new [test](http://35.161.250.236:6543/tests/view/591ee5be6e23db7f3bc38d6e) shows.

@ddugovic : Thank you.

**Comment by ddugovic** [comment]
Thank you @alwey for the great contribution!

I have broken my patch 220e62cc270f2cb18857bcd50d8cf915a66f2601 into four patches.  I scrapped the passed pawn bonus, two of the patches failed, and the remaining [patch](http://github.com/ddugovic/Stockfish/commit/220e62cc270f2cb18857bcd50d8cf915a66f2601#diff-c74eb33120f9e932f7cfc0be07fa91d2R342) with some tuning (or ingenuity) can probably be made into a non-functional speedup on the basis that a losers chess position has only two kings.

**Comment by ddugovic** [comment]
@alwey I did some code golfing: 451858cb2e054b78408fdbb8de6117bbbfd5999b and parent 736bacc44a31a0da7ac56d1bc0298b97fb9884e7 with `bench losers` results (non-PGO out of 10):

```
base =    1327935 +/- 5781
test =    1335578 +/- 6733
diff =       7642 +/- 5717
speedup = 0.005755
```

and `bench losers` results (PGO out of 10):

```
base =    1362385 +/- 7938
test =    1363124 +/- 8488
diff =        739 +/- 5086
speedup = 0.000543
```

and `bench chess` results (PGO out of 10):

```
base =    1306876 +/- 10106
test =    1310062 +/- 1400
diff =       3185 +/- 10420
speedup = 0.002438
```

**Comment by alwey** [comment]
@ddugovic : The speed differences are about the order or perhaps a bit smaller than I would have guessed.
I wonder whether one would be a able to use std::maps in an intelligent way to handle (essentially optional) properties of variants and subvariants. E.g. many properties only vary between variants.  Just sometimes a subvariant needs special attention, e.g. `Losers` /wrt material values.

**Comment by ddugovic** [comment]
Maybe even `std:unordered_map` merits [consideration](http://stackoverflow.com/a/3198171)!  On the other hand, maybe compiling with C++17 offers even more options (both in terms of data storage/lookup algorithms and in terms of template parameter usage).

**Comment by ppigazzini** [comment]
After [gcc 7 port](https://github.com/official-stockfish/Stockfish/commit/e9f26cccdde7ca6e0941bb4b9066665a68c5bc42) @official-stockfish shoud be ready for C++17. Windows instruction to use gcc 7.1.0 added in the [wiki](https://github.com/ddugovic/Stockfish/wiki/Running-the-worker-on-Windows#advanced-topics)

**Comment by alwey** [comment]
Better be a bit conservative /wrt to necessary compiler and library versions.

**Comment by ianfab** [comment]
Since there have been many patches for losers chess on top of the original change, I created a branch where all of these are reverted to have a direct comparison. I tested it and created PR #353.

**Comment by ddugovic** [comment]
If anyone wants contributor rights for this repository (for merging upstream changes) let me know.
