### ISSUE TITLE
Signature for variant

### ISSUE THREAD

**Issue by ppigazzini** [ddugovic/Stockfish#347]
Issue started in #345 

@ianfab 
>Yes, I thought about that when I started to adjust fishtest for variants, but was unsure whether that should be changed. The main problem is that we would not be able to test versions before the [bench command for variants was introduced](https://github.com/ddugovic/Stockfish/commit/0a444f69a6849d4efc7c29510e362df7a38de187) if we used the variant bench results (same if we used `bench all`, which was introduced even later), or at least it would require some hacks to make it possible. Furthermore, it is quite a useful check to see that standard chess functionality does not change by a patch. I am still torn between the two possibilites, because both have their advantages and drawbacks.
>>I think I just found a weakness in fishtest: Signatures are tested for standard chess instead of the test's actual variant.

I don't know the SF C++ code but, if it's already in order to generate a signature for a variant, should be not complicated to modify the fishtest code:
1. to verify the variant signature for base and new
2. to verify that the standard signature does not change from base to new when testing a variant. This step does not require to entering also the standard signature in the [new test page](http://35.161.250.236:6543/tests/run). Worker already knows the variant name, so it's possible to deal with the case of monthly regression test for standard chess (where standard signature changes from base to new).

Other changes required:
* fishtest server side (e.g. [Actions](http://35.161.250.236:6543/actions))
* ~[SF Makefile](https://github.com/ddugovic/Stockfish/blob/master/src/Makefile), adding an external variable to bench for the variant.~ [PGO](https://en.wikipedia.org/wiki/Profile-guided_optimization) for the variant is not a requirement
* [wiki page](https://github.com/ddugovic/Stockfish/wiki/Creating-my-first-test)

**Comment by ddugovic** [comment]
To clarify, the Stockfish change would simply be to expose the `bench [variant]` command in `Makefile`?

**Comment by ddugovic** [comment]
Regarding:

> Furthermore, it is quite a useful check to see that standard chess functionality does not change by a patch.

I entirely agree; and if the patch gains Elo for a variant it's OK if that variant's signature changes.

It might be useful to have the `bench all` number, although right now the `bench all` signature differs for `debug=yes` and `debug=no` and might be nondeterministic?  I'm working on that...

**Comment by ppigazzini** [comment]
@ddugovic I think that I was wrong, PGO specialized for a single variant is not a requirement, so Makefile unchanged.

**Comment by ddugovic** [comment]
I mean, PGO specialized for a single variant is a cool idea and as long as I don't have to support it I don't mind its addition.

**Comment by ddugovic** [comment]
Note that upstream merge 20ab503 breaks `bench [variant]` and I'm unsure what's a good way to re-implement it without breaking `bench` for standard chess.

**Comment by ianfab** [comment]
I think it is pretty straightforward. I mainly copy-pasted my previous implementation of bench for variants and it seems to work: https://github.com/ddugovic/Stockfish/pull/396. It might require some more testing though to make sure that it does not break anything else.

**Comment by ddugovic** [comment]
Ah, that makes sense (and the Chess960 flag should be irrelevant since the X-FENs are valid).

**Comment by ddugovic** [comment]
Today I learned that `bench all` "nodes searched" numbers differ for `optimize=yes` and `optimize=no`, which I'm pretty sure should not be the case.

Also (more simply) `bench horde 16 1 4` numbers differ.

**Comment by ddugovic** [comment]
I forgot to mention this earlier, but now all the `bench` numbers match irrespective of `debug` and `optimize` settings.
