### ISSUE TITLE
Thread about "collecting PV" for Stockfish :

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#371]
http://www.talkchess.com/forum/viewtopic.php?t=64256

**Comment by ddugovic** [comment]
Our relevant source code is [search.cpp](http://github.com/ddugovic/Stockfish/blob/master/src/search.cpp#L448) selecting the longest PVs of each thread.

What TalkChess is suggesting is using a PVS Search to extract a longer PV from a search terminated early?

**Comment by ddugovic** [comment]
That forum thread contains [an example](http://vajoletchess.blogspot.it/2013/11/a-modern-way-to-collect-principal.html) for those unfamiliar with PV search.

HGM's [answer](http://talkchess.com/forum/viewtopic.php?topic_view=threads&p=718613&t=64256) is consistent with what Stockfish already does.
