### ISSUE TITLE
Does that means that zh was improved by 97 (Elo 30-08-17) ?

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#400]
30-08-17 crazyhouse | merge2 | diff | ELO: 97.39

That would be crazy good :-)

**Comment by ianfab** [comment]
No, it's a comparison between two possible ways of merging an upstream change, where the naive approach would have lost 97 Elo.

**Comment by ddugovic** [comment]
I do look forward to the next release & [regression test](http://35.161.250.236:6543/regression) thanks both to @ianfab crazyhouse parameter tweaks and upstream SEE simplification bf485f4affc37cd408a65b66b8a3aad059bad5f3 .
