### ISSUE TITLE
Should setting UCI_Variant reinitialize the position?

### ISSUE THREAD

**Issue by niklasf** [ddugovic/Stockfish#418]
@programfox just stumbled upon this. I *think* it was working differently in the past, but I am not sure. Anyway it's a minor inconvenience:

```
uci
setoption name UCI_Variant value giveaway
```
It will now still play with standard rules.
```
position startpos
```
Giveaway rules activated.

Are there any downsides to resetting the position when UCI_Variant is set?

**Comment by niklasf** [comment]
Never mind, it was probably always like this.

**Comment by ddugovic** [comment]
I suppose setting the default position (followed by sending an `info` string with the accepted variant & FEN to the client) could be useful; I'm no longer trying to support "hybrid" variants (except 960 versions of variants).

Right now setting `UCI_Variant` merely sends an `info` string to the client to indicate the default position for that variant.
