### ISSUE TITLE
Atomic endgames with adjacent kings

### ISSUE THREAD

**Issue by ianfab** [ddugovic/Stockfish#42]
Endgames in Atomic chess can be very different from standard chess. Positions with adjacent kings usually are impossible to win if there are not many pieces left on the board. It has been reported several times that the engine incorrectly evaluates KQ vs. K. The same applies to several other material configurations. Suggested solutions:
- use scale factor to make evaluation more drawish when kings are adjacent
- use Stockfish's specialized evaluation functions for respective endgame material configurations

All KX v .K endgames with adjacent kings are drawn with perfect play. Studies for endgames with more pieces can be found here: http://www.nicklong.net/chess/atomic/mates.htm (Edit: a few entries in the tables can be proven wrong with atomic tablebases, so if in doubt better use tablebases.)

**Comment by ddugovic** [comment]
I created a new branch [variant_endgame](http://github.com/ddugovic/Stockfish/tree/variant_endgame) as a sandbox for such ideas.

**Comment by ianfab** [comment]
@ddugovic Great. I propose a minor change in #191.

**Comment by ianfab** [comment]
I tested the variant_endgame branch against master in atomic chess, since this should be the only variant where there is a functional difference. The test results (stopped after 5000 games) at 10''+0.1'' are:
```
LLR: 0.47 (-2.94,2.94) [0.00,10.00]
Total: 5000 W: 1656 L: 1581 D: 1763
```
It probably is much more useful for analysis than for engine vs. engine games, but anyway there seems to be a small Elo gain.

**Comment by ianfab** [comment]
@ddugovic Results at 30''+0.3'' look good, so I think you can merge the variant_endgame branch into master.
```
LLR: 2.97 (-2.94,2.94) [0.00,10.00]
Total: 4318 W: 1363 L: 1237 D: 1718
```

**Comment by ianfab** [comment]
We can maybe add more endgame functions in the future, but for now I think I can close this.

**Comment by ddugovic** [comment]
Yes, sorry I forgot to close this upon merging the branch.
