### ISSUE TITLE
No such option: UCI_Variant

### ISSUE THREAD

**Issue by sabfrompc** [ddugovic/Stockfish#427]
I downloaded a copy of the current source and compiled it using MinGW. I have done this with previous versions which all had the UCI_Variant option. However, when typing:
"setoption name UCI_Variant value Atomic"
I get greeted with:
"No such option: UCI_Variant"

I'm guessing this is related to this change:
https://github.com/ddugovic/Stockfish/commit/5fe80f1620c66547e96abd9622e77d21f4c74d12
This also broke the gui that I was using as it no longer shows an option for atomic.

**Comment by ianfab** [comment]
@sabfrompc 
If I remember correctly, "No such option" is only displayed if it can not match the option name, not if the value mismatches (in the latter case it would simply play standard chess). Please run the command `uci` to display which options are there. From your description I expect `UCI_Variant` to be missing there, which should not happen if you compiled current master (or any other version less than about one year old) of this fork. Can you please check whether you had really checked out the source code of this fork before compiling?

The code you linked is only run if the command starts with `bench`, so I think that should not be related to this issue.
