### ISSUE TITLE
Indirect king attacks in Atomic chess

### ISSUE THREAD

**Issue by ianfab** [ddugovic/Stockfish#43]
So far indirect king attacks are neither prevented from being pruned nor extended like checks are. Therefore the engine often underestimates indirect king attacks and does only correctly evaluate its consequences at high depths. A simple example is the position after 1. Nf3 f6 2. Nc3: 2... Nh6 is a good move, but because of the line 3. Nd5 e6 4. Nxc7, 2...Nh6 is pruned. It takes a lot of time for the engine to see that 4... Ng4 is winning. This should not happen. I think indirect king attacks could be adequatly taken account of by the following steps:
- prevent them from being pruned
- extend them by one ply like checks
- incorporate threats of possible indirect king attacks into the king safety evaluation, just like check threats

**Comment by ddugovic** [comment]
This all sounds logical and difficult to identify because the king (or adjacent pieces) can move.

**Comment by ianfab** [comment]
I was very confident that this would give a big elo gain, but when I implemented the first two bullet points it  was a regression. Probably this is because there are many harmless indirect king attacks, e.g. by the queen targeting pawns on the 7th rank, but the pawns can simply advance. So it could make sense to only extend them if the attacked piece cannot move, which would make it more similar to checks (you can only move the king, block or capture).

**Comment by ddugovic** [comment]
But requiring the attacked piece (pawn) to be fixed would fail to address this point:

> It takes a lot of time for the engine to see that 4... Ng4 is winning. This should not happen.

**Comment by ianfab** [comment]
The f2 pawn is blocked by the knight on f3. However, even if it were not black would still be winning because of ...Nf2 and the trapped queen on d1. In the latter case only one of the two indirect king attacks would match my criterion, but it might still help to find the variation. Either way, since I currently do not have a better idea I will try it.

**Comment by ianfab** [comment]
In case someone has an idea on this, the patch in [this test](http://35.161.250.236:6543/tests/view/588690b76e23db4d9f2e293f) contains some useful code to test ideas on indirect king attacks.

**Comment by ianfab** [comment]
I found that in a [recent game on lichess](https://lichess.org/02Rx6EQ2/black#33) level 8 blundered, because it overlooked a dangerous indirect king attack leading to a forced mate. It seems like an interesting test position, since it also involves two times attacking and capturing the pinned piece to discover checks. I so far did not manage to find a patch that reduces the time until it finds mate (not even testing for Elo if it does not even perform well in the position where it is supposed to).

Output of current master in the position after the blunder:
```
setoption name UCI_Variant value atomic
position fen 2k2r2/p3p2p/5r2/1p1p1n2/8/3PP3/PPPB2PP/R3KR2 w Q - 5 17 moves e1c1
go depth 20
info string variant atomic startpos rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
info depth 1 seldepth 1 multipv 1 score cp -87 nodes 34 nps 17000 tbhits 0 time 2 pv f5e3
info depth 2 seldepth 2 multipv 1 score cp -84 nodes 132 nps 66000 tbhits 0 time 2 pv f5e3 f1f6
info depth 3 seldepth 3 multipv 1 score cp -100 nodes 221 nps 110500 tbhits 0 time 2 pv f5e3 f1f6 b5b4
info depth 4 seldepth 4 multipv 1 score cp -124 nodes 514 nps 171333 tbhits 0 time 3 pv f5e3 f1f5 f6f5 d1e1
info depth 5 seldepth 5 multipv 1 score cp -93 nodes 814 nps 203500 tbhits 0 time 4 pv f5e3 f1f5 f6f5 d1e1 f8f2
info depth 6 seldepth 6 multipv 1 score cp -47 nodes 2932 nps 366500 tbhits 0 time 8 pv f5e3 f1f5 e7e5 d1f1 e5e4 c1b1
info depth 7 seldepth 7 multipv 1 score cp -23 nodes 6097 nps 435500 tbhits 0 time 14 pv f5e3 f1f5 e7e5 d1f1 e5e4 c1b1 c8b7
info depth 8 seldepth 8 multipv 1 score cp -42 nodes 7128 nps 445500 tbhits 0 time 16 pv f5e3 f1f5 e7e5 c2c4 b5c4 d1f1 e5e4 f5f6
info depth 9 seldepth 14 multipv 1 score cp -45 nodes 17114 nps 475388 tbhits 0 time 36 pv f5e3 f1f2 e7e5 g2g4 f6f2 d1f1 f8f2 f1f2 e5e4
info depth 10 seldepth 13 multipv 1 score cp -5 nodes 32125 nps 573660 tbhits 0 time 56 pv f5e3 f1f5 e7e5 d3d4 e5e4 c2c4 e4e3 c4c5 e3e2 d1e1
info depth 11 seldepth 15 multipv 1 score cp 0 nodes 67302 nps 715978 tbhits 0 time 94 pv f5e3 c1b1 f6f2 f1f2 f8f2 d1d2 f2f1 d2d1 f1f2
info depth 12 seldepth 10 multipv 1 score cp 0 nodes 74726 nps 739861 tbhits 0 time 101 pv f5e3 c1b1 f6f2 f1f2 f8f2 d1d2 f2f1 d2d1 f1f2
info depth 13 seldepth 10 multipv 1 score cp 0 nodes 86620 nps 780360 tbhits 0 time 111 pv f5e3 c1b1 f6f2 f1f2 f8f2 d1d2 f2f1 d2d1 f1f2
info depth 14 seldepth 17 multipv 1 score cp 0 nodes 107497 nps 853150 tbhits 0 time 126 pv f5e3 c1b1 f6f2 f1f2 f8f2 d1d2 f2f1 d2d1 f1f2
info depth 15 seldepth 10 multipv 1 score cp 0 nodes 146050 nps 942258 tbhits 0 time 155 pv f5e3 c1b1 f6f2 f1f2 f8f2 d1d2 f2f1 d2d1 f1f2
info depth 16 seldepth 22 multipv 1 score mate 9 nodes 345703 nps 1289936 tbhits 0 time 268 pv f6c6 c2c3 b5b4 e3e4 f5e3 d2e3 c6c7 f1f6 e7f6 d1h1 b4c3 c1d1 c7c1 d1e2 f8f2 e2e3 d5e4
info depth 17 seldepth 18 multipv 1 score mate 9 nodes 350828 nps 1294568 tbhits 0 time 271 pv f6c6 c2c3 b5b4 e3e4 f5e3 d2e3 c6c7 f1f6 e7f6 d1f1 b4c3 c1d1 c7c1 d1d2 c1d1 d2e2 f8f1
info depth 18 seldepth 18 multipv 1 score mate 9 nodes 355275 nps 1301373 tbhits 0 time 273 pv f6c6 c2c3 b5b4 e3e4 f5e3 d2e3 c6c7 f1f6 e7f6 d1f1 b4c3 c1d1 c7c1 d1d2 c1d1 d2e2 f8f1
info depth 19 seldepth 18 multipv 1 score mate 9 nodes 360752 nps 1307072 tbhits 0 time 276 pv f6c6 c2c3 b5b4 e3e4 f5e3 d2e3 c6c7 f1f6 e7f6 d1f1 b4c3 c1d1 c7c1 d1d2 c1d1 d2e2 f8f1
info depth 20 seldepth 18 multipv 1 score mate 9 nodes 367823 nps 1318362 tbhits 0 time 279 pv f6c6 c2c3 b5b4 e3e4 f5e3 d2e3 c6c7 f1f6 e7f6 d1f1 b4c3 c1d1 c7c1 d1d2 c1d1 d2e2 f8f1
bestmove f6c6 ponder c2c3
```

**Comment by ddugovic** [comment]
Now that f36c4c8d01c1487a44b97b83684b6b2f43201e2b is merged (so SF is less likely to play into lost endgames), I'll try re-tuning some parameters and retry some old ideas.

**Comment by ddugovic** [comment]
be5a2f015e45886e32867b4559ef51dd694a3cec fixes several TT bugs related to checkmate which may have undermined our earlier efforts.  Time permitting I'll run some more tests.

**Comment by ddugovic** [comment]
Another example of a misplayed attack: https://lichess.org/YIQo8JtV/white#36
