### ISSUE TITLE
Cannot start fishtest cmd

### ISSUE THREAD

**Issue by Nordlandia** [ddugovic/Stockfish#433]
I've created account and followed everything per "Running the worker on Windows"

Once i launch fishtest.bat cmd opens for about 200ms then close. 

I really want to contribute CPU time.

**Comment by ianfab** [comment]
Unfortunately, I currently do not know what could cause this. @ppigazzini Do you have an idea?

**Comment by ppigazzini** [comment]
I just installed multivariant fishtest in a clean Windows 10 64 bit virtual machine following step-by-step the wiki: it works.
1. check the username password with a login in the page [New Test](http://35.161.250.236:6543/tests/run)
2. if username and/or password have some special characters, write they within a couple of double quote:
``cmd /k C:\Python27\python.exe -i C:\fishtest-master\worker\worker.py --concurrency <n_cores> "<username>" "<password>"``

**Comment by ianfab** [comment]
@ppigazzini Thanks a lot.

**Comment by Nordlandia** [comment]
The system can not find the path specified.

**Comment by ppigazzini** [comment]
@Nordlandia The batch expects to find these files:
1. `C:\Python27\python.exe`
2. `C:\fishtest-master\worker\worker.py`
3. `C:\msys64\mingw64\bin\g++.exe`

I got your error message only if I write a wrong path for python, so check to have `C:\Python27\python.exe` or change the path according your python 2.7.x installation.

If you are contributing also in official fishtest be sure that `C:\fishtest-master\` is the path for multi variant fishtest, or change the path accordingly.

**Comment by Nordlandia** [comment]
Fishtest-Worker-Portable is working just fine. 

Someone create _Portable_ worker for variant as well and nobody has to experience this.

**Comment by ppigazzini** [comment]
@Nordlandia you have not answered the questions about:
1. your python path installation: from your error message it seems not in `C:\Python27\python.exe`
2. if `C:\fishtest-master\` is the path of your multi variant fishtest installation

If you have a custom python path installation, update the startup batch file. A space in the path is a problem, you should write this:

``
cmd /k ""C:\Your Python27 path\python.exe" -i "C:\Your fishtest-master path\worker\worker.py" --concurrency 3 "<username>" "<password>""
``

Off-topic: I like only short and well documented installer:
1. provide simple know how to the user
2. only one installation of the tool chain packages (python, msys, mingw-w64) to run both official and multivariant fishtest (simply use two startup batch files)
3. easier to keep updated the packages

I updated the wiki page with some disclaimer

**Comment by Nordlandia** [comment]
C:\Python27\python.exe is in root folder in C drive (first folder)
C:\fishtest-master\worker\worker.py same as above
C:\msys64\mingw64\bin\g++.exe same as above 

I convert .txt into bat easily then edit bat file in text editor. 


Why doesn't bat file work?

@echo off
SET PATH=C:\msys64\mingw64\bin\g++.exe;C:\msys64\usr\bin;%PATH%
cmd /k C:\Python27\python.exe -i C:\fishtest-master\worker\worker.py --concurrency <> <> <>

**Comment by ppigazzini** [comment]
Yes, the bat content should be in your case (I'm supposing: concurrency=3, nordlandia as username and upyr_password as password)
```
@echo off
SET PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
cmd /k C:\Python27\python.exe -i C:\fishtest-master\worker\worker.py --concurrency 3 "nordlandia" "your_password"
```

Debug steps:
1. Check python.
Open a command prompt and write
```
C:\Python27\python.exe
```
You should view
```
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

2.  Check python with fishtest.
Open a command prompt and write
```
C:\Python27\python.exe -i C:\fishtest-master\worker\worker.py
```

You should view
```
Worker version 64 connecting to http://35.161.250.236:6543
'make' is not recognized as an internal or external command,
operable program or batch file.

Exception running games:
Traceback (most recent call last):
  File "C:\fishtest-master\worker\worker.py", line 88, in worker
    run_games(worker_info, password, remote, run, task_id)
  File "C:\fishtest-master\worker\games.py", line 366, in run_games
    setup_engine(new_engine, worker_dir, run['args']['resolved_new'], repo_url, worker_info['concurrency'])
  File "C:\fishtest-master\worker\games.py", line 132, in setup_engine
    subprocess.check_call(MAKE_CMD + ' -j %s' % (concurrency), shell=True)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'make profile-build COMP=mingw ARCH=x86-64-modern -j 3' returned non-zero exit status 1
Task exited
```
3. check mingw-w64.
Open a command prompt and write
```
SET PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
g++ -v
```
You should view
```
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-7.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev1, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 7.2.0 (Rev1, Built by MSYS2 project)
```

**Comment by Nordlandia** [comment]
It seems that "--concurrency 3" solved the issue. 

--concurrency <n_cores> <username> <password>

Remove "<n_cores>" solved the issue. 

Is it possible to contribute towards TwoKings?

**Comment by ianfab** [comment]
@Nordlandia Nice to hear that it is working now. There currently is no way to restrict contribution to specific variants, it will pick any task that is to be processed.

Thanks @ppigazzini for your help.

**Comment by ppigazzini** [comment]
Wiki page updated writing more clear instructions.
Added also the instruction to write a `custom_make.txt` file to have faster binaries with a recent CPU (Intel Haswell or later).

@Nordlandia: IIRC your 7 cores worker is a i7-5960X (Haswell-E). For that worker you can write a `C:\fishtest-master\worker\custom_make.txt` file with this text:

```
make profile-build ARCH=bmi2 COMP=mingw -j 7
```

**Comment by ppigazzini** [comment]
@Nordlandia: sorry for my typo. For your worker with i7-5960X (Haswell-E) you can write a `C:\fishtest-master\worker\custom_make.txt` file with this text:

```
make profile-build ARCH=x86-64-bmi2 COMP=mingw -j 7
```
