### ISSUE TITLE
Fishtest error on 10 year old CPU

### ISSUE THREAD

**Issue by Nordlandia** [ddugovic/Stockfish#441]
Intel E5200 2-core

Exception running games:
Traceback (most recent call last):
  File "C:\fishtest-master\worker\worker.py", line 88, in worker
    run_games(worker_info, password, remote, run, task_id)
  File "C:\fishtest-master\worker\games.py", line 366, in run_games
    setup_engine(new_engine, worker_dir, run['args']['resolved_new'], repo_url, worker_info['concurrency'])
  File "C:\fishtest-master\worker\games.py", line 132, in setup_engine
    subprocess.check_call(MAKE_CMD + ' -j %s' % (concurrency), shell=True)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'make profile-build COMP=mingw ARCH=x86-64-modern -j 1' returned non-zero exit status 1
Task exited

**Comment by ddugovic** [comment]
I've not used mingw, however there must be some reason that command `make profile-build COMP=mingw ARCH=x86-64-modern -j 1` exits with status 1... I wonder if development tools are installed (commands such as `make` and the compiler)?

**Comment by ianfab** [comment]
There used to be some issues with the profile build for the tuning branch using gcc, but I do not know whether something similar could be the reason here. At least the report coincides with the submission of tuning sessions.

**Comment by Nordlandia** [comment]
This computer stays on 24/7. So why not allocate it's cpu time to framework than doing nothing.

**Comment by ianfab** [comment]
@Nordlandia Thanks for your contributions. Since it is an old CPU, `ARCH=x86-64-modern` could be a problem. Have you tried to use a custom make command with `ARCH=x86-64`? If this also does not work, then you could try to use `build` instead of `profile-build`.

**Comment by Nordlandia** [comment]
@ianfab this CPU does not support popcnt and other instructions. Ideally only native x64 compile is to be used.

**Comment by Nordlandia** [comment]
How do i make "Command 'make profile-build COMP=mingw ARCH=x86-64-modern -j 1" turns into 

Command 'make profile-build COMP=mingw ARCH=x86-64 -j 1 ?

**Comment by ianfab** [comment]
@Nordlandia You can find it in the wiki: https://github.com/ddugovic/Stockfish/wiki/Running-the-worker-on-Windows#override-default-make-command

**Comment by Nordlandia** [comment]
I added custom_make.txt with make profile-build ARCH=x86-64 COMP=mingw -j 2

Error still present.

**Comment by ianfab** [comment]
Does the error message (`CalledProcessError: Command 'make profile-build COMP=mingw ARCH=x86-64-modern -j 1' returned`) show the new make command (as a check that the custom make is actually used)? You can also still try whether using build instead of profile-build fixes the issue.

**Comment by Nordlandia** [comment]
CalledProcessError: Command 'make profile-build ARCH=x86-64 COMP=mingw -j 1' returned non-zero exit status 1
Task exited

**Comment by MichaelB7** [comment]
A 10 year old computer? - will it have enough CPU power ?  It it sees less than 750k nps , it may be more detrimental than good, i.e, distort the results or introduce noise.  Have you tried the 32 bit option ? Also you may want to change -O3 to -O2 or -O1 to see if that works.

**Comment by Nordlandia** [comment]
The idea is to allocate 1 / 2 cores for fishtest as this computer stays on 24/7. It is connected to a widescreen tv with internet. So i can watch twich, youtube, chess from tv-chair comfortably 😆

**Comment by MichaelB7** [comment]
😊👊

**Comment by ppigazzini** [comment]
@ddugovic problem solved in https://github.com/ddugovic/Stockfish/issues/446, I missed this thread. I think that you can close this threads.
