### ISSUE TITLE
CI bench mismatches

### ISSUE THREAD

**Issue by ianfab** [ddugovic/Stockfish#442]
The CI tests currently always fail. If I understand correctly, this is because `Replace easyMove with simple scheme` has somehow been merged twice, which causes the scripts to find the wrong reference bench. I think this should be fixed by the next upstream merge, but I wanted to mention it here since I was a bit confused why the tests failed and maybe it is the same for others.

**Comment by ddugovic** [comment]
Thanks, this confused me as well.

**Comment by ianfab** [comment]
After the latest upstream merge, the bench matches, but the tests still fail due to the failed assertion mentioned in https://github.com/ddugovic/Stockfish/issues/432#issuecomment-341960512, but since there already is a dedicated thread for that, I am closing this.
