### ISSUE TITLE
Fishtest Worker Portable

### ISSUE THREAD

**Issue by Nordlandia** [ddugovic/Stockfish#446]
Is it possible to fork (see link) to prevent problems with older computers. 

https://github.com/glinscott/fishtest/wiki/A-portable-fishtest-worker-for-Windows-64-bit

**Comment by ppigazzini** [comment]
MSYS2 should not have a problem with an older HW: simply write a "custom_make.txt" with `make profile-build ARCH=x86-64 COMP=mingw`.

With an older OS (Windows XP or Windows Server 2003) you need to install MSYS and MinGW-w64 according [this instruction](https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Windows#mingw-w64--msys-deprecated-use-only-with-windows-xp-and-windows-server-2003)).

IMO in official fishtest there are some workers with a wrong configuration (e.g. too much cores allocated wrt the normal CPU load) because the portable installer, so I prefer a solution that provides some basic knowledge to the CPU contributor to avoid errors.

**Comment by Nordlandia** [comment]
CPU is intel E5200 2-Core

Does not work on launch

Exception running games:
Traceback (most recent call last):
  File "C:\fishtest-master\worker\worker.py", line 88, in worker
    run_games(worker_info, password, remote, run, task_id)
  File "C:\fishtest-master\worker\games.py", line 366, in run_games
    setup_engine(new_engine, worker_dir, run['args']['resolved_new'], repo_url, worker_info['concurrency'])
  File "C:\fishtest-master\worker\games.py", line 130, in setup_engine
    subprocess.check_call(make_cmd, shell=True)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'make profile-build ARCH=x86-64 COMP=mingw -j 1' returned non-zero exit status 1
Task exited

**Comment by ppigazzini** [comment]
What version of Windows are you using? (e.g. Windows 10 64 bit)

**Comment by Nordlandia** [comment]
Yeah

**Comment by ppigazzini** [comment]
I ran a worker with a Q6600 that is one year older than your E5200.

Open a command prompt and write these commands to check the MSYS2 installation
```bat
SET PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
make -v
g++ -v
```

**Comment by Nordlandia** [comment]
Command prompt don't understand the raw input. 

From which default directory shall i run it from?

**Comment by ppigazzini** [comment]
It works with the prompt opened in any directory.
Check to have the files `C:\msys64\mingw64\bin\g++.exe` and `C:\msys64\usr\bin\make.exe`
I have updated the [windows's wiki page](https://github.com/ddugovic/Stockfish/wiki/Running-the-worker-on-Windows) trying to be more clearer respect the old version.

**Comment by ppigazzini** [comment]
If you start a Windows PowerShell cli, start a command prompt with the command `cmd` before pasting the test commands.

**Comment by Nordlandia** [comment]
C:\WINDOWS\system32>g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-7.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32
--host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/includ
e --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,objc,
obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable
-fully-dynamic-string --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-versio
n-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-regis
try --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=
/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev1, Built by MSYS2 project' --with-bugurl=https://
sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 7.2.0 (Rev1, Built by MSYS2 project)

**Comment by Nordlandia** [comment]
launching fishtest.bat with modified txt file

old CPU:

make profile-build ARCH=x86-64 COMP=mingw -j <n_jobs>

Worker version 64 connecting to http://35.161.250.236:6543
The syntax of the command is incorrect.

Exception running games:
Traceback (most recent call last):
  File "C:\fishtest-master\worker\worker.py", line 88, in worker
    run_games(worker_info, password, remote, run, task_id)
  File "C:\fishtest-master\worker\games.py", line 366, in run_games
    setup_engine(new_engine, worker_dir, run['args']['resolved_new'], repo_url, worker_info['concurrency'])
  File "C:\fishtest-master\worker\games.py", line 130, in setup_engine
    subprocess.check_call(make_cmd, shell=True)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'make profile-build ARCH=x86-64 COMP=mingw -j <1_jobs>' returned non-zero exit status 1
Task exited

**Comment by ppigazzini** [comment]
```make profile-build ARCH=x86-64 COMP=mingw -j 1```

**Comment by Nordlandia** [comment]
It works! 😉 😄

**Comment by Nordlandia** [comment]
Do you recommend allocate 1-CPU during daytime and 2-Core during nights?

I rarely use this computer during the day. Beside watching chess event and twitch/youtube sometimes.

**Comment by ppigazzini** [comment]
Fishtest limits the max concurrency to the "number of cores -1", check this [line of code](https://github.com/ianfab/fishtest/blob/master/worker/worker.py#L143)

In my experience is better to always leave a threads free for the Windows tasks.
I'm not against the uses of hypertrheading, though.

**Comment by Nordlandia** [comment]
My twin laptops (Lenovo G70-80) has hyperthreading disabled for Stockfish.exe and Base.exe with processor affinity tool called **Process Lasso**

I bet Quality Beats Quantity concerning variant improvment. 

![processlasso](https://user-images.githubusercontent.com/26534454/32844098-c77ea36e-ca21-11e7-9ba5-f1c0b5922697.png)

**Comment by Nordlandia** [comment]
If hypertrheading isn't hurting framework games. Then i can allocate 3-threads on each laptop (6 in total)

Isn't hypertrheading bad?

**Comment by ppigazzini** [comment]
With my Quad Core + HT (max threads=8) I keep HT always on.
Usually I start a worker with concurrency=3, when there are tests with SMP=7 threads then I restart  the worker with concurrency=7

In my tests there is less noise with a PC dedicated only at fishtest and a worker with concurrency="max threads-1" than with a PC used toview youtube, browser etc and a worker with concurrency=1

**Comment by ppigazzini** [comment]
I suppose that you are Litago94 in official fishtest :)

**Comment by Nordlandia** [comment]
Yes

**Comment by Nordlandia** [comment]
@ppigazzini fishtest variant don't have physical core restriction like official fishtest. 

E.g you can allocate allocate all "real cores" as long once HT is for OS.

**Comment by ppigazzini** [comment]
@Nordlandia sorry to reject your opinion, both official and multivariant have this check
https://github.com/ianfab/fishtest/blob/master/worker/worker.py#L143

So the max value of concurrency is "n. threads - 1" (with HT on, n. threads = 2 * n. cores)

The batch file of the Portable Installer check the number of cores and set the max value of the concurrency to "n. cores - 1".

BTW you now can run official fishtest using MSYS2, following the [wiki instruction](https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Windows).
You could change the folder names in "C:\fishtest-master-of" for official and "C:\fishtest-master-mv" multivariant and change the path in the starting batch files.

Official:
```bat
@echo off
SET PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
cmd /k C:\Python27\python.exe -i C:\fishtest-master-of\worker\worker.py --concurrency <n_cores> <username> <password>
```

Multivariant:
```bat
@echo off
SET PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
cmd /k C:\Python27\python.exe -i C:\fishtest-master-mv\worker\worker.py --concurrency <n_cores> <username> <password>
```

**Comment by Nordlandia** [comment]
Nevermind that. I found the cause of the time losses on one of my laptop dedicated for fishtest. 

CPU constantly fluctuating around 15-30%, when the computer is just sitting idle. Task Manager shows it.

Solution for me: uninstall Avast and install Avira.

**Comment by ppigazzini** [comment]
@Nordlandia if you think that this issue is solved, please consider to close it.
