### ISSUE TITLE
How to compile stockfish on windows

### ISSUE THREAD

**Issue by ppigazzini** [ddugovic/Stockfish#457]
Moved from https://github.com/ddugovic/Stockfish/issues/445 to avoid OT

@Nordlandia AppVeyor and TravisCI are tools for Continuous Integration (for Windows and Linux platform), check the GitHub project homepage ([click here](https://github.com/ddugovic/Stockfish#overview)), you should view two green icons with the text "build: passing".
They could be used on GitHub for these goals:
1. build a binary for each single code commit to test the compile process
2. execute the binary and run some tests, to check for errors in execution
3. save the binary under the tab "Release"

If you are interested in compiling yourself multivariant stockfish:

1. write the file C:\msys64\home\YOUR_USERNAME\makefish.sh (change YOUR_USERNAME) with this text:

```bash
#!/bin/bash
# makefish.sh

# update and install packages: after the first run you can comment this instruction
# pacman -S --noconfirm unzip make mingw-w64-x86_64-gcc

# download the Stockfish source code
wget https://github.com/ddugovic/Stockfish/archive/master.zip
unzip master.zip
cd Stockfish-master/src

# build the executable
# keep only the section that fits your CPU architecture, delete the other sections 

# use this section with CPU older than Sandy Bridge:
make profile-build ARCH=x86-64 COMP=mingw
strip stockfish.exe
mv stockfish.exe ../../stockfish_x64.exe
make clean

# use this section with Sandy Bridge and Ivy Bridge CPU:
make profile-build ARCH=x86-64-modern COMP=mingw
strip stockfish.exe
mv stockfish.exe ../../stockfish_x64_modern.exe
make clean

# use this section with Haswell and newer CPU:
make profile-build ARCH=x86-64-bmi2 COMP=mingw
strip stockfish.exe
mv stockfish.exe ../../stockfish_x64_bmi2.exe
make clean

cd
```
2. open a **MSYS2 MinGW 64-bit** console
3. install unzip running this command `pacman -S --noconfirm unzip` . Step 3 is needed once, don't run it in future
4. execute this command `bash makefish.sh` to build multivariant stockfish

Notes
* makefish.sh is a simple text file. Use notepad to create this file in "C:\msys64\home\YOUR_USERNAME"
* press "Windows Key + Q" to open "Search Windows", write "mingw" and chose from the menu "MSYS2 MinGW 64-bit"
* write this command `ls`, you should view the file "makefish.sh" (or "makefish.sh.txt")
* run the command `bash makefish.sh` (or `bash makefish.sh.txt`)

**Comment by ddugovic** [comment]
Cool, since these instructions work it may be useful to add them to this repo's wiki

**Comment by Nordlandia** [comment]
Unfortunately on my primary machine i skipped step 3, now i can't launch MSYS2 MinGW 64-bit console

Worked on my laptop though, following recipe / all steps.

**Comment by ppigazzini** [comment]
[Wiki page](https://github.com/ddugovic/Stockfish/wiki/Building-Multi-Variant-Stockfish) added with an upgraded version of the building script (check/installation of required packages, check of CPU architecture). Added also the instruction for linux.

**Comment by Nordlandia** [comment]
"C:\msys64\home\USERNAME\cutechess\projects\lib\NUL"

This file can't be removed "Invalid MS-DOS Function"

**Comment by ppigazzini** [comment]
@Nordlandia Are you trying to build cutechess?

**Comment by ppigazzini** [comment]
@Nordlandia added in the [wiki home page](https://github.com/ddugovic/Stockfish/wiki) the links to the development snapshots builds for any CPU/OS
