### ISSUE TITLE
TwoKings illegal castling bug. 

### ISSUE THREAD

**Issue by Nordlandia** [ddugovic/Stockfish#458]
![illegalbug](https://user-images.githubusercontent.com/26534454/32956537-54cb117e-cbb9-11e7-98cb-32ebb19d0ed0.png)

Capturing the king without royal-power does not forfeits castling rights, i.e capturing the king on f1/f8 does not mean king on e1/e8 is unable to castle either sides. 

[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "New game"]
[Black "?"]
[Result "*"]
[Variant "illegal"]
[SetUp "1"]
[FEN "rnbqkknr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKKNR w - - 0 1"]
[PlyCount "39"]

{[#] Training} 1. d2-d4 d7-d5 2. Nb1-c3 Ng8-f6 3. Bc1-g5 Nf6-e4 4. Nc3-e4 d5-e4
5. Bg5-f4 Bc8-e6 6. f2-f3 Qd8-d5 7. Bf4-c7 Nb8-d7 8. f3-e4 Qd5-e4 9. Qd1-d3
Qe4-d5 10. e2-e4 Qd5-c6 11. Bc7-a5 Be6-c4 12. Qd3-f3 Bc4-f1 13. Qf3-f1 Qc6-e4
14. Qf1-e2 Qe4-d4 15. Ba5-c3 Qd4-h4 16. g2-g3 Qh4-a4 17. Ng1-f3 Qa4-a6 18.
Qe2-a6 b7-a6 19. Bc3-a5 h7-h5 {CuteChess display illegal move. Although if i'm
not wrong, castling is legal if the non-royal king get captured earlier in the
game.} 20. O-O-O *

[Event "?"]
[Site "CuteChess 1.0.0 | i7-5960X 4.1GHz 8-Core"]
[Date "2017.11.17"]
[Round "?"]
[White "stockfish_x64_bmi2"]
[Black "stockfish_x64_bmi2"]
[Result "0-1"]
[PlyCount "38"]
[Termination "illegal move"]
[TimeControl "180+2"]
[Variant "twokingssymmetric"]

1. d4 {+0.21/28 16s} d5 {-0.16/27 6.6s} 2. Nc3 {+0.32/23 1.4s}
Nf6 {-0.12/25 4.1s} 3. Bg5 {+0.18/27 18s} Ne4 {-0.14/26 15s}
4. Nxe4 {+0.30/25 3.3s} dxe4 {-0.01/23 1.3s} 5. Bf4 {+0.32/28 7.8s}
Be6 {-0.25/27 13s} 6. f3 {+0.30/26 6.7s} Qd5 {-0.33/27 7.7s}
7. Bxc7 {+0.37/26 3.2s} Nd7 {-0.34/25 3.1s} 8. fxe4 {+0.40/32 24s}
Qxe4 {-0.21/25 5.3s} 9. Qd3 {+0.43/26 2.3s} Qd5 {-0.35/29 9.7s}
10. e4 {+0.59/26 5.8s} Qc6 {-0.40/26 6.6s} 11. Ba5 {+0.61/25 3.0s}
Bc4 {-0.37/27 3.5s} 12. Qf3 {+0.57/26 5.6s} Bxf1 {-0.50/29 24s}
13. Qxf1 {+0.60/25 4.1s} Qxe4+ {-0.60/27 4.0s} 14. Qe2 {+0.62/26 5.3s}
Qxd4 {-0.40/27 10s} 15. Bc3 {+0.57/26 6.8s} Qh4+ {-0.43/28 6.8s}
16. g3 {+0.62/26 3.6s} Qa4 {-0.42/28 7.9s} 17. Nf3 {+0.42/28 6.8s}
Qa6 {-0.57/28 5.1s} 18. Qxa6 {+0.55/26 2.5s} bxa6 {-0.51/26 3.8s}
19. Ba5 {+0.58/29 9.0s} h5 {-0.38/26 2.0s, White makes an illegal move: e1c1}
0-1

On ICC you're able to castle if the non-royal king get captured earlier in the game. Confirmed by testing 3min ago of this writing.

**Comment by ianfab** [comment]
@Nordlandia So if I understand correctly, Stockfish conforms to the ICC rules, but this is inconsistent with how it is implemented in cutechess, right?

**Comment by Nordlandia** [comment]
It is related to cutechess rules. So no worries 👌

**Comment by alwey** [comment]
The first game the game was set up without castling rights. At least cutechess is correct here.

**Comment by Nordlandia** [comment]
@alwey twokingssymmetrics does not allow castling if the f1/f8 king get captured.

**Comment by alwey** [comment]
This is a bug - my bad. I already found the cause. BTW castling rights will be removed if one of the kings moves. But this is ok. We already talked about this.

**Comment by Nordlandia** [comment]
@alwey this _nuance_ was probably forgotten on the day of implementing/coding.

**Comment by alwey** [comment]
I guess this was no accident, but the server maintainers of ICC simply announced as rules what had been implemented.

**Comment by ianfab** [comment]
@Nordlandia Why are there two PGNs? It looks like both are the same game but with different PGN headers. If Stockfish castled in a game started from an FEN without castling rights (first game), there would be a bug. However, the header looks strange, so maybe the FEN stated there was not really used.

**Comment by Nordlandia** [comment]
@ianfab Chessbase 14 allow illegal setup positions, for example make diagram for variant chess. Fritz gui do not.

**Comment by ddugovic** [comment]
It appears that Stockfish respects the castling rights in the input FEN and doesn't illegally castle?

```
Stockfish 181117 64 BMI2 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
setoption name UCI_Variant value twokings
info string variant twokings startpos rnbqkknr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKKNR w KQkq - 0 1
position fen rnbqkknr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKKNR w - - 0 1 moves g1f3 g8f6 g2g3 g7g6 f1g2 f8g7 e1g1
d

 +---+---+---+---+---+---+---+---+
 | r | n | b | q | k |   |   | r |
 +---+---+---+---+---+---+---+---+
 | p | p | p | p | p | p | k | p |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   | n | p |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   | N | P |   |
 +---+---+---+---+---+---+---+---+
 | P | P | P | P | P | P | K | P |
 +---+---+---+---+---+---+---+---+
 | R | N | B | Q | K |   |   | R |
 +---+---+---+---+---+---+---+---+

Fen: rnbqk2r/ppppppkp/5np1/8/8/5NP1/PPPPPPKP/RNBQK2R w - - 2 4
Key: 2E2DD879FD75EF92
Checkers: 
```

**Comment by Nordlandia** [comment]
CuteChess solved this bug.

**Comment by ppigazzini** [comment]
@Nordlandia great work!
Please, re-open this issue.
I need to know from @ianfab and @alwey if I must build an updated build of cutechess-cli for fishtest after this commit https://github.com/cutechess/cutechess/commit/c31ff038280ff202dd320da11f66986e7baf5ef0

**Comment by ianfab** [comment]
@ppigazzini I think it is not that urgent as it does not lead to crashes, but "only" to incorrect adjudication of games, and we currently anyway do not have a two kings test running. Updated compiles would nevertheless be nice if you find the time. I have to keep in mind to also rename the symmetric two kings variant in the fishtest code as soon as cutechess is updated.

**Comment by alwey** [comment]
@ppigazzini: The change is an improvement for Two Kings Chess, but only makes a difference in rare cases. But my patch may increase the instabilty of the Giveaway variant in cutechess because there is a hidden bug in it. I used some workarounds to minimise its effect. Now one of these guards has been removed. The problem: cutechess may give false positives for illegal moves in Giveaway when castling is allowed.

So am not really happy with both the older and the newer version.

**Comment by ppigazzini** [comment]
@ianfab new builds updated to today development version tested in fishtest with my workers (ubuntu, windows 10, WSL), here the PR https://github.com/ianfab/FishCooking/pull/6

@alwey let me know when you will have a version that make you happy

**Comment by alwey** [comment]
@ppigazzini : 

> let me know when you will have a version that make you happy

promised

**Comment by ianfab** [comment]
@ppigazzini Thanks, I have merged the PR. I also increased the version number in fishtest to force the workers to download the new binaries.
