### ISSUE TITLE
Old compiles of Official Stockfish in GitHub releases & tags

### ISSUE THREAD

**Issue by ppigazzini** [ddugovic/Stockfish#462]
@ddugovic @ianfab The [GitHub releases & tags](https://github.com/ddugovic/Stockfish/releases) show old compiles of Official Stockfish, I suggest to clean them to avoid misunderstanding.

I found in [this page](http://www.unibia.com/unibianet/developer/delete-all-tags-and-releases-git-and-github) some simple instructions to clean all old Tags and Releases on GitHub, they worked fine on my [Stockfish repo](https://github.com/ppigazzini/Stockfish). You are more expert than me with git/GitHub, so take with a grain of salt my suggestion :)

If I'm not wrong @niklasf has configured Travic CI and Appveyor to populate automatically the [fishnet's releases](https://github.com/niklasf/Stockfish/releases).

**Comment by ddugovic** [comment]
Done.
