### ISSUE TITLE
Invalid MS-DOS Function

### ISSUE THREAD

**Issue by Nordlandia** [ddugovic/Stockfish#473]
Couple of weeks ago i messed up the msys64 directory by skipping a stage. Now i've removed everything except the following directory. I can't remove it. 

I really want to use the original directory so i don't have to edit so many paths. 

"C:\msys64\home\Your_Username\cutechess\projects\lib\NUL"

**Comment by niklasf** [comment]
https://stackoverflow.com/a/17883854/722291 may help to get rid of the NUL file. Then you should be able to remove the directories as usual.

**Comment by Nordlandia** [comment]
@niklasf thanks for helping me out. How should i proceed in cmd?

C:\msys64\home\Your_Username\cutechess\projects\lib\NUL

C:\> rename \\.\C:\..\NUL. deletefile.txt
C:\> del deletefile.txt
