### ISSUE TITLE
Variant framework timeout

### ISSUE THREAD

**Issue by Nordlandia** [ddugovic/Stockfish#496]
Once in a while the framwork is idle for relatively long time. May i ask the cause for this pause.

**Comment by ddugovic** [comment]
Is there a timeout?  I wonder...

I think:

```
Pending - 0 tests 0.0 hrs
Active - 0 machines 0 cores 0.00M nps (0.00M total nps) 0 games/minute
```

means that the source code isn't writing itself and that developers haven't recently submitted patches?

**Comment by Nordlandia** [comment]
Thx for info.

**Comment by ddugovic** [comment]
I have an idea for SPSA tuning sessions (based upon an upstream merge which forced me to change parameters)... 82d9b04c79414ea16065afaa56004a68efe276af
