### ISSUE TITLE
Syzygy for Antichess, Atomic

### ISSUE THREAD

**Issue by ddugovic** [ddugovic/Stockfish#511]
https://github.com/ddugovic/Stockfish/tree/tbprobe_revert and `master` should produce the same results (`debug=yes`) for:

```
setoption name SyzygyPath value [PATH]
bench 128 1 22
```

**Comment by ddugovic** [comment]
```
$ ls ../tb/
KBvK.rtbw  KBvK.rtbz  KNvK.rtbw  KNvK.rtbz  KPvK.rtbw  KPvK.rtbz  KQvK.rtbw  KQvK.rtbz  KRvK.rtbw  KRvK.rtbz
$ export SYZYGY_PATH='/home/lila/Stockfish/tb'
$ cat test4.txt 
setoption name SyzygyPath value /home/lila/fishnet/tb
bench 128 1 10
$ cat test4.txt | ./stockfish
```

**Comment by ddugovic** [comment]
There's still more work to do on this one, although now I think(?) everything merged properly.

**Comment by ddugovic** [comment]
These commits are focused on:

* restoring chess functionality lost during the upstream merge
* future-proofing using `#ifdef` so future bugs can be fixed by disabling variant code
* reintroducing variant functionality lost during the upstream merge

**Comment by ddugovic** [comment]
Workaround: set `SyzygyProbeLimit `to 4.  So now the SSCCE of the problem is:

```
setoption name SyzygyPath value /home/lila/Stockfish/tb
setoption name SyzygyProbeLimit value 5
bench 128 1 1
```

**Comment by ddugovic** [comment]
24071511266d984c50a9677551bf45ef8e09060d (revert) is the only known fix but there has to be a simpler solution...

SSCCE (5-man syzygybases installed, `Makefile` has all variants disabled, expected functionality "do not segfault"):

```
  "8/3p3B/5p2/5P2/p7/PP5b/k7/6K1 w - - 0 1",
  "8/3k4/8/8/8/4B3/4KB2/2B5 w - - 0 1",    // draw
```

```
setoption name SyzygyPath value /home/lila/Stockfish/tb
setoption name SyzygyProbeLimit value 4
bench 128 1 6
```

**Comment by ddugovic** [comment]
Cool, sorry to have made you endure that entire video! 😆  I've added a comment that the interesting part starts just before the 2-hour mark.

Best of luck with your final exams!

**Comment by Nordlandia** [comment]
Shall we close #471 as it can be duplicate?

**Comment by niklasf** [comment]
#471 is a different issue. Here we temporarily removed support for *all* variants (except standard), even those that were previously supported.
