### ISSUE TITLE
Investigate TT performance

### ISSUE THREAD

**Issue by ddugovic** [ddugovic/Stockfish#514]
I added an assertion to help discover why DROP moves are being considered at all for non-crazyhouse chess.

```
$ cat test.fen
setoption name UCI_Variant value crazyhouse
rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
setoption name UCI_Variant value chess
rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1

$ ./stockfish bench chess 1 1 8 test.fen
Stockfish 2018-04-05 64 BMI2 Multi-Variant by D. Dugovic, F. Fichter et al.
info string variant chess startpos rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
info string variant crazyhouse startpos rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR[] w KQkq - 0 1

Position: 1/2
info depth 1 seldepth 1 multipv 1 score cp 194 nodes 20 nps 20000 tbhits 0 time 1 pv e2e3
info depth 2 seldepth 2 multipv 1 score cp 56 nodes 77 nps 77000 tbhits 0 time 1 pv e2e3 d7d6
info depth 3 seldepth 3 multipv 1 score cp 155 nodes 217 nps 108500 tbhits 0 time 2 pv d2d3 d7d6 g1f3
info depth 4 seldepth 4 multipv 1 score cp 94 nodes 446 nps 223000 tbhits 0 time 2 pv d2d3 d7d6 g1f3 b8c6
info depth 5 seldepth 5 multipv 1 score cp 57 nodes 1156 nps 289000 tbhits 0 time 4 pv d2d3 d7d6 g1f3 g8f6 c1d2
info depth 6 seldepth 6 multipv 1 score cp 70 nodes 1933 nps 322166 tbhits 0 time 6 pv e2e3 e7e6 b1c3 b8c6 g1f3 g8f6
info depth 7 seldepth 7 multipv 1 score cp 76 nodes 3925 nps 356818 tbhits 0 time 11 pv b1c3 d7d5 d2d4 g8f6 g1f3 b8c6 e2e3
info depth 8 seldepth 9 multipv 1 score cp 112 nodes 6778 nps 398705 tbhits 0 time 17 pv e2e4 d7d5 e4d5 g8f6 d2d4 d8d5 b1c3 d5e6 P@e3
bestmove e2e4 ponder d7d5
info string variant chess startpos rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1

Position: 2/2
info depth 1 seldepth 1 multipv 1 score cp 106 nodes 20 nps 10000 tbhits 0 time 2 pv e2e4
info depth 2 seldepth 2 multipv 1 score cp 30 nodes 79 nps 39500 tbhits 0 time 2 pv d2d4 d7d5
info depth 3 seldepth 3 multipv 1 score cp 77 nodes 122 nps 61000 tbhits 0 time 2 pv d2d4 d7d5 g1f3
info depth 4 seldepth 4 multipv 1 score cp 30 nodes 214 nps 107000 tbhits 0 time 2 pv d2d4 d7d5 g1f3 g8f6
info depth 5 seldepth 5 multipv 1 score cp 73 nodes 376 nps 125333 tbhits 0 time 3 pv d2d4 d7d5 g1f3 g8f6 b1c3
info depth 6 seldepth 6 multipv 1 score cp 49 nodes 832 nps 208000 tbhits 0 time 4 pv d2d4 d7d5 g1f3 g8f6 b1c3 b8c6
stockfish: position.h:1065: bool Position::capture(Move) const: Assertion `is_ok(var, m)' failed.
Aborted (core dumped)
```

**Comment by ianfab** [comment]
Do you really intend to add/change all of these assertions in the code or is it just for debugging purposes?

**Comment by ddugovic** [comment]
Originally I had intended to add/change these assertions, but now I see this is much too complicated (in particular, `is_ok(Move)` exists for purposes other than assertion, unlike `pos_is_ok`).

I should have submitted a patch for only:
* early return in `pseudo_legal`
* assertion in `legal` that drop moves are only considered in crazyhouse

and can take a closer look at `is_ok(Move)` separately.

**Comment by ianfab** [comment]
Yes, that sounds like a good approach.

**Comment by ddugovic** [comment]
Reading `search.cpp` carefully, I see that `is_ok(Move)` is only called for already-played (valid) moves.  Other consumers of `is_ok(Move)` are in assertion statements (non-functional), so there is no risk of a drop move occurring in a non-crazyhouse variant.

Next I'll consider king promotion moves.

**Comment by ddugovic** [comment]
I know king promotions are uncommon, but generating the entire move list in response to a TT king promotion move is unfortunate.

**Comment by Nordlandia** [comment]
In "losing chess" the king is rather an "commoner" because of no royal properties. 

Commoner promotions is available as result.

**Comment by ddugovic** [comment]
For disambiguation purposes I (and ICC/FICS) refer to variants by these names: giveaway, suicide, losers.

Lichess concocted "antichess" which is a hybrid of giveaway and suicide variants.

**Comment by ddugovic** [comment]
1ec97748b8c452d74cb87ead1667ad4d87644cf0 does not improve performance.

If (for non-antichess, non-extinction variants) a king promotion TT move is found from the cache, `pseudo_legal` will generate the entire legal move list and verify that that move list does not contain the king promotion move.
