### ISSUE TITLE
Status of bughouse

### ISSUE THREAD

**Issue by niklasf** [ddugovic/Stockfish#524]
Looking for other compiler flags, I see that -DBUGHOUSE is enabled by default. What's the status of the implementation? Maybe it should be disabled by default or moved entirely to a seperate branch?

**Comment by ddugovic** [comment]
Multi-Variant Stockfish has a working bughouse implementation (captured pieces are not added to the player's hand) with minimal code complexity:

```
$ grep -n bughouse *.cpp *.h
position.cpp:1376:              if (! is_bughouse())
position.cpp:1392:          if (! is_bughouse())
position.cpp:1774:              if (! is_bughouse())
position.h:204:  bool is_bughouse() const;
position.h:827:inline bool Position::is_bughouse() const {
types.h:214:"bughouse",
```

But I suppose if nobody's using it (UCI might not even support it) maybe it should be disabled by default.

**Comment by niklasf** [comment]
Ah, never mind then. I thought it wasn't even working.
