### ISSUE TITLE
Search/evaluation feature Elo table

### ISSUE THREAD

**Issue by ianfab** [ddugovic/Stockfish#530]
In order to get an overview of how well certain search and evaluation features work for different variants, I summarized the results of my tests (STC, 2000 games each) in a spreadsheet:
https://docs.google.com/spreadsheets/d/1vt1fjXeh1ME5Vuz71FkuSSP_mByy-pmQOgpInMlEn1I/edit?usp=sharing

A few observatations from my side:
- There are a couple of negative values, so we might gain some Elo by skipping the respective code for certain varians (and might later reenable an improved version to have a positive Elo effect).
- Mobility bonus does not gain any Elo for crazyhouse. That seems highly surprising to me, so there should be room for improvement here.
- The passed pawn bonus is also about Elo neutral for crazyhouse. I suspect that it might be too big considering that the piece values are lower and dynamic factors more important compared to standard chess.

The table is still far from complete, so feel free to submit tests for measuring Elo of other parts of the code.

**Comment by danikyyzz** [comment]
guys it's clear as a slap just everything can't work perfectly

**Comment by ddugovic** [comment]
Great idea, however search and evaluation code keep changing so this would need to be re-measured with every release.  A bit of a moot point since my own development will be on hold for now.
