### ISSUE TITLE
internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by stas730** [ddugovic/Stockfish#539]
make profile-build ARCH=x86-64-modern -j2
…
Step 3/4. Building optimized executable ...
…
`g++ -o stockfish benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o thread.o timeman.o tt.o uci.o ucioption.o syzygy/tbprobe.o -lgcov -m64 -Wl,--no-as-needed -lpthread -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-use -fno-peel-loops -fno-tracer -pedantic -Wextra -Wshadow -m64 -DANTI -DATOMIC -DBUGHOUSE -DCRAZYHOUSE -DDISPLACEDGRID -DEXTINCTION -DGRID -DHORDE -DKOTH -DLOOP -DLOSERS -DRACE -DSLIPPEDGRID -DSUICIDE -DTHREECHECK -DTWOKINGS -DTWOKINGSSYMMETRIC -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto
lto1: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
lto-wrapper: fatal error: g++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
Makefile:527: recipe for target 'stockfish' failed
make[2]: *** [stockfish] Error 1
make[2]: Leaving directory '/home/username/Stockfish/variant/Stockfish/src'
Makefile:549: recipe for target 'gcc-profile-use' failed
make[1]: *** [gcc-profile-use] Error 2
make[1]: Leaving directory '/home/username/Stockfish/variant/Stockfish/src'
Makefile:447: recipe for target 'profile-build' failed
make: *** [profile-build] Error 2
`

**Comment by ddugovic** [comment]
I want to help... I'm trying to understand how `lto1: internal compiler error: Segmentation fault` could have occurred.

**Comment by ianfab** [comment]
@stas730 Could you please try to compile with `ARCH=x86-64`? The only possible explanation I can come up with is that maybe your CPU is not compatible with the architecture you are compiling for, which could lead to a segfault due to unsupported CPU instructions. Otherwise I have no idea how this could happen.

**Comment by stas730** [comment]
Maybe, some variants files are wrong then.

**Comment by ddugovic** [comment]
Perhaps although both Travis CI and Appveyor aren't reporting any errors (on Linux, OS X, or Windows), only your version of GCC:
https://travis-ci.org/ddugovic/Stockfish
https://ci.appveyor.com/project/ddugovic/Stockfish

**Comment by ddugovic** [comment]
Travis CI and Appveyor also use `make profile-build` to perform profile-guided optimization, for example:
https://travis-ci.org/ddugovic/Stockfish/jobs/427861949
