### ISSUE TITLE
Build broken with -DUSELONGESTPV

### ISSUE THREAD

**Issue by niklasf** [ddugovic/Stockfish#546]
Seems like this flag is no longer supported:

```
search.cpp: In Elementfunktion »virtual void MainThread::search()«:
search.cpp:460:7: Fehler: »longestPVThread« wurde in diesem Gültigkeitsbereich nicht definiert
   if (longestPVThread != this)
       ^~~~~~~~~~~~~~~
search.cpp:460:7: Anmerkung: empfohlene Alternative: »bestThread«
   if (longestPVThread != this)
       ^~~~~~~~~~~~~~~
       bestThread
```

Worth reviving?

**Comment by ddugovic** [comment]
Perhaps worth reviving/re-implementing; I forget which upstream commit changed to a "voting" mechanism which I struggled with gracefully merging.

**Comment by ddugovic** [comment]
ba928db15b341eaa6feee41886afe2b3854a978c broke this feature.  Now to try to figure out how to reintroduce this feature...!

**Comment by ddugovic** [comment]
Upstream keeps changing the Multi-PV code, so at this time this probably isn't worth reviving.
