### ISSUE TITLE
About crazyhouse regression test 07-12-18 

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#548]
I see a regression test from 07-12-18 with only +15.12  improvement.
But I see only one improvement 3 weeks ago, worth 65 rating points !

How is it possible ?
Thanks !

Details : 
07-12-18 	ia 	crazyhouse 	fishnet-291118 	diff 	
ELO: 15.12 +-15.0 (95%) LOS: 97.6%
Total: 2000 W: 1019 L: 932 D: 49
	
13-11-18 	ia 	crazyhouse 	zh_see 	diff 	
ELO: 65.02 +-21.6 (95%) LOS: 100.0%
Total: 1000 W: 580 L: 395 D: 25

**Comment by ddugovic** [comment]
Indeed, playing strength of this fork has plateaued exactly as Fabian says.  Many of my new ideas this year have failed. 

I'm curious what's causing a small regression in Horde performance but haven't had time to look into it.  Possibly official-stockfish/Stockfish#1839 may expose an issue with promotion threat evaluations, we'll see.

**Comment by Vinvin20** [comment]
Thanks for your explanations !
