### ISSUE TITLE
Input sanitization

### ISSUE THREAD

**Issue by ddugovic** [ddugovic/Stockfish#551]
See official-stockfish/Stockfish#905.  My sole concern is privilege escalation; I don't care if inputs are validated.

**Comment by ddugovic** [comment]
In hindsight, this isn't a solvable problem unless I validate all possible inputs, which is more than I am prepared to handle.

**Comment by niklasf** [comment]
It's not a big deal anyway. In practice Stockfish should not be exposed directly to untrusted input, there will always be a GUI or wrapper script. And of course no one should be running Stockfish with elevated privileges.
