### ISSUE TITLE
SF 10 Crazyhouse for Windows 7 64bit on WinBoard 4.8.0

### ISSUE THREAD

**Issue by yellow-panther** [ddugovic/Stockfish#553]
Hello ddugovic,
I use https://github.com/ddugovic/Stockfish/releases/download/variant_sf_10/stockfish-windows-x86_64-modern.exe with WinBoard 4.8.0 GUI http://www.open-aurec.com/wbforum/viewtopic.php?f=19&t=51528 but your compilation works neither with UCI nor WinBoard/CECP:
UCI~ variant Crazyhouse is not supported, no implementation is possible
WinBoard/CECP ~ SF10 Crazyhouse can be embedded , but does not work (no moves are executed)

"QueensGambit" https://github.com/QueensGambit/CrazyAra/releases made similar expiriences.
What can be done to solve this problem? My IvyBridge CPU does not support bmi2-structure

Regards

**Comment by ddugovic** [comment]
Hello yellow-panther!

Although not being a Windows expert, I'll investigate this (Multi-Variant Stockfish is a UCI engine; it's possible to verify this by opening a command shell and running it, then typing command `uci` to see options):
> UCI~ variant Crazyhouse is not supported, no implementation is possible

**Comment by ddugovic** [comment]
When I run that Stockfish EXE and input the "uci" command, I see a full `UCI_Variant` option list.  However even after adding to WinBoard 4.8.0 engine list:

```
"Stockfish" -fcp stockfish-windows-x86_64-modern -fd "../Stockfish" /fUCI
```

that version of WinBoard did not indicate that Stockfish (using WinBoard's UCI-to-CECP adapter) can play variants.  Therefore I recommend trying a newer WinBoard version, perhaps from https://www.gnu.org/software/xboard/ or even the AA build referenced at http://talkchess.com/forum3/viewtopic.php?t=62331&start=10 and at http://talkchess.com/forum3/viewtopic.php?t=62331&start=80

**Comment by yellow-panther** [comment]
Hello Daniel,
the modern SF10 Crazyhouse runs successfully now on CuteChess 1.0.0 for Windows https://github.com/cutechess/cutechess/releases/download/gui-1.0.0/cutechess_setup.exe and Windows AA beta http://hgm.nubati.net/WinBoard-AA.zip

My Intel i5 Quad with  Ivybridge micro-architecture does not support .bmi2 of course because Haswell is here the minimum

Regards,

**Comment by yellow-panther** [comment]
[White Sjaak141"]
[Black "SF"]
[Result "0-1"]
[PlyCount "44"]
[TimeControl "40/300"]
[Variant "crazyhouse"]

1. d4 {+0.14/13 4.9s} d5 {-0.28/23 8.5s} 2. Nf3 {+0.16/13 4.7s}
Bf5 {-0.07/22 3.8s} 3. Nc3 {+0.08/13 6.1s} e6 {+0.18/21 5.3s}
4. h3 {-0.01/13 6.6s} Nc6 {+1.65/21 5.1s} 5. a3 {+0.05/13 5.0s}
Nf6 {+1.78/20 3.8s} 6. g4 {-0.12/13 7.8s} Bg6 {+2.55/21 7.2s}
7. Nh4 {+0.04/13 9.9s} Ne4 {+3.87/20 3.5s} 8. Nxg6 {-0.06/12 7.8s}
Nxf2 {+4.05/20 7.0s} 9. Nxh8 {+1.74/10 6.6s} Qh4 {+9.10/20 3.2s}
10. Bg5 {+2.28/10 6.4s} Nd3+ {+10.08/19 2.2s} 11. Kd2 {+1.53/2 0.001s}
Qxg5+ {+10.84/20 9.3s} 12. e3 {+1.99/9 4.9s} B@e1+ {+11.30/18 3.2s}
13. Kxd3 {+2.33/9 4.7s} Bxc3 {+10.73/23 21s} 14. B@f4 {+3.05/9 4.3s}
P@c4+ {+28.80/19 4.2s} 15. Ke2 {+0.34/9 4.7s} Qxf4 {+29.12/19 3.4s}
16. exf4 {-0.43/9 4.5s} Nxd4+ {+34.64/16 6.2s} 17. Qxd4 {-2.10/8 5.3s}
Bxd4 {+34.93/17 6.3s} 18. Rh2 {-3.66/8 9.0s} B@f3+ {+M9/29 4.5s}
19. Ke1 {-M8/11 2.3s} P@f2+ {+M7/39 2.6s} 20. Rxf2 {-M6/10 0.016s}
Bxf2+ {+M5/73 6.2s} 21. Kxf2 {-M4/2 0.001s} N@e4+ {+M3/91 6.1s}
22. Kxf3 {-M2/2 0s} Q@f2# {+M1/127 0.038s, Black mates} 0-1

**Comment by ddugovic** [comment]
Excellent @yellow-panther !  I have added those URLs to https://github.com/ddugovic/Stockfish/wiki .

**Comment by HGMuller** [comment]
Note that the WinBoard 4.8 download has WinBoard configured to run UCI engine through the (included) Polyglot adapter, and that the latter only supports normal Chess (and perhaps Chess960). To run UCI variants you will need to use a recent version of the UCI2WB adapter (as included in the WinBoard-AA download), and configure WinBoard to use that instead of Polyglot. By running once with the Additional option

-adapterCommand {UCI2WB debug "%fcp" "%fd"}

(which in the WinBoard-AA distro would already be pre-configured).

**Comment by MichaelB7** [comment]
Hi HGM,
What is the best to get the latest xboard for Mac.

There is is an xboard on macports , but I don’t think it’s the latest. 

Thanks in advance.

**Comment by HGMuller** [comment]
Op Za, 14 december, 2019 5:38 pm schreef Michael Byrne:
> Hi HGM,
> What is the best to get the latest xboard for Mac.
>

I am not really into Apple stuff, but I would think the OSX App bundle (
http://www.open-aurec.com/wbforum/viewtopic.php?f=19&t=53680 ) is
reasonably up to date. If you are set up to build it from source you can
use the version in my on-line repository (
http://hgm.nubati.net/cgi-bin/gitweb.cgi ), v4.9.x branch. There is a
thread on WinBoard forum that discusses how to activate the OSX-specific
features ( http://www.open-aurec.com/wbforum/viewtopic.php?f=2&t=54390 ).

>
> There is is an xboard on macports , but I donât think itâs the
> latest.
>
> Thanks in advance.
>
>
> Sent from my iPhone
>
>

**Comment by ddugovic** [comment]
Thanks, I've uploaded https://github.com/ddugovic/Stockfish/wiki with download links.
