### ISSUE TITLE
PyChessGUI 1.0.0 and SF Variant

### ISSUE THREAD

**Issue by yellow-panther** [ddugovic/Stockfish#555]
Hello ddugovic,

Tamás Bajusz a.k.a. gbtami wrote to me: "PyChess 1.0.0 supports all variants it supported before (including crazyhouse). Variant-Stockfish (and all stockfish fork) is running OK in PyChess. If you have any problem installing it just file an issue at https://github.com/pychess/pychess/issues "

http://pychess.org/download/ - http://pychess.org/about/

Regards,

**Comment by ddugovic** [comment]
Thanks, I've added PyChess to the list of GUIs which support the UCI_Variant command at https://github.com/ddugovic/Stockfish/wiki .
