### ISSUE TITLE
Interest in a fork for a multi-agent Bughouse engine?

### ISSUE THREAD

**Issue by jlind0** [ddugovic/Stockfish#556]
I recently published an article describing how a Subject Matter Expert Turing Test could be devised around the 4 player game “Bughouse”. In order for the AI to pass the test there probably wouldn’t need to be substantial advancements in chess engines as much as a bit of a rethink of existing ones.

Interestingly this would be an example of AI collaborating with humans and other AI, as such I believe this would be a worthwhile project and I was wondering if you, or anyone you know, would be interested in founding/contributing to such a project.

The article can be found: https://www.linkedin.com/pulse/subject-matter-expert-turing-test-bughouse-chess-variant-lind/

**Comment by ddugovic** [comment]
I'm still puzzled about how to respond to this...

* I want to recommend contacting bughouse communities, but I don't know them and enthusiasm isn't the same as interest.  Some players might like to have intelligent AI teammates who both calculate and communicate at a high level, but on what site could they play?  Popular sites have strict no-cheating policies.
* If the project is successful, its techniques could be transferred to other domains, incidentally spelling the demise of competitive chess.  I am skeptical about this project, even if somehow it finds sponsorship.
* Regardless what your goal is, http://talkchess.com/ might be a good place to start discussion with engine developers.
