### ISSUE TITLE
Playing strength regressions between fishnet-180120 and fishnet-120919

### ISSUE THREAD

**Issue by ianfab** [ddugovic/Stockfish#570]
Regression tests are still running but for some variants the regression is already statistically significant:
* Crazyhouse: ~-80 Elo, http://www.variantfishtest.org:6543/tests/view/5e2577a56e23db46beba4c97
* Giveaway: ~-150 Elo, http://www.variantfishtest.org:6543/tests/view/5e2579b56e23db46beba4c9c
* Atomic: ~150 Elo, http://www.variantfishtest.org:6543/tests/view/5e257d7a6e23db46beba4c9e
* Horde: ~30 Elo, http://www.variantfishtest.org:6543/tests/view/5e257d836e23db46beba4ca0

**Comment by ianfab** [comment]
In view of b50326b740bd8361a507b9ffafa95d1f1cdc00fd I guess this is expected.

**Comment by ddugovic** [comment]
For the most part I agree.  I'll look into the atomic regression.
