### ISSUE TITLE
Crazyhouse evaluation is broken

### ISSUE THREAD

**Issue by benwh1** [ddugovic/Stockfish#571]
Usually, the startpos for crazyhouse is evaluated at around +1 to +2 for white, but in the current version, the startpos is evaluated as being better for black (usually around -1, but it fluctuates a lot).

I ran a quick (1/2+0) 20 game tournament in cutechess of the current version against an old version from around a year ago, and the current version lost 2 - 18. In several positions, the old version evaluated the position as being around +5 for white, while the current version evaluated it around -5 (as in, winning for black) and only later went positive once it was obviously losing.

I tried a git bisect and got this:

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
c6839a26155c18dbb7700175971fe01c5a67b01c
f27339d35b6c8ccd1f83914b334c89111e62f320
07b8597685f78502c0513d1e0b2d2822c11ade0a
```

**Comment by ddugovic** [comment]
Thanks, my bot is now declining crazyhouse challenges until I can see an example of this issue...
https://lichess.org/@/GodelEscherBot/search?perf=18 does indicate some losses although I do not yet know how to see the regression.  I'm starting by looking at https://lichess.org/uQ1Bpm7o/black#63 unless you have example FENs I can try...?

**Comment by ddugovic** [comment]
OK, I see an evaluation shift:

```
#!/bin/bash
make clean && git checkout master~100
git log HEAD | grep "\b[Bb]ench[ :]\+[0-9]\{7\}" | head -n 1 | sed "s/[^0-9]*\([0-9]*\).*/\1/g" > git_sig
export benchref=$(cat git_sig)
echo "Reference bench:" $benchref
rm git_sig
make build ARCH=x86-64-bmi2 debug=yes && mv stockfish stockfish_master
make clean && git checkout master

./stockfish_master bench crazyhouse 16 1 13 test.fen depth |& sed -u -e 's/info depth //' | sed -u -e 's/seldepth //' | sed -u -e 's/multipv //' | sed -u -e 's/tbhits 0 //' | tee 1.txt
./stockfish bench crazyhouse 16 1 13 test.fen depth |& sed -u -e 's/info depth //' | sed -u -e 's/seldepth //' | sed -u -e 's/multipv //' | sed -u -e 's/tbhits 0 //' | tee 2.txt
sdiff --width=192 1.txt 2.txt
```
