### ISSUE TITLE
compile flag to disable standard chess

### ISSUE THREAD

**Issue by bftjoe** [ddugovic/Stockfish#579]
Hi is there any way to add a compile flag to disable support for standard chess/chess960? I have a patch for https://github.com/niklasf/fishnet/issues/105and was wondering if variants could also get a performance boost?

**Comment by ddugovic** [comment]
@bftjoe http://xyproblem.info/ ... adding such a flag could not help anywhere near as much as disabling antichess does (~5% speedup).

If you care about any particular variant (e.g. atomic or crazyhouse) try disabling all the variant feature flags except the one which most interests you.

**Comment by bftjoe** [comment]
I could do that but I don't know if lichess devs would be comfortable distributing 6+ different binaries with fishnet. I guess I could ask them....

**Comment by ddugovic** [comment]
I think the variant flag which causes the greatest slowdown is antichess (5% when I measured years ago) whereas others are about 2-3% each I think.

**Comment by bftjoe** [comment]
Right but there are other issues with running multiple binaries simultaneously such as memory consumption for hash tables. Not sure what tradeoffs they want to make but if I can get a 15-20+% boost by using regular Stockfish for Standard/960 and then another 2-3% on all variants by disabling chess/960 on the multi variant side it would be worthwhile imo.

**Comment by ddugovic** [comment]
Maybe 0.0001% of the Stockfish code is 960-specific so I estimate you'd be looking at a 0% speedup by disabling it.
