### ISSUE TITLE
Segfault in Atomic variant

### ISSUE THREAD

**Issue by ianfab** [ddugovic/Stockfish#58]
I get a segfault with current master when running:
uci
setoption name UCI_Atomic value true
position startpos
go infinite

I have found that this happens since d9c51fc, but so far I do not know what causes the segfault.

**Comment by ddugovic** [comment]
Duplicated using `gdb`:
Thread 2 "stockfish" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6b43700 (LWP 21717)]
Position::slider_blockers (this=0x7ffff6b44128, sliders=<optimized out>, s=SQ_NONE, pinners=@0x7ffff6b3bb90: 0) at position.cpp:597
597             if (b & pieces(color_of(piece_on(s))))
(gdb) bt
#0  Position::slider_blockers (this=0x7ffff6b44128, sliders=<optimized out>, s=SQ_NONE, pinners=@0x7ffff6b3bb90: 0) at position.cpp:597
#1  0x0000000000428dad in Position::set_check_info (this=0x7ffff6b44128, si=0x7ffff6b3ba20) at position.cpp:358
#2  0x000000000042d772 in Position::do_move (this=this@entry=0x7ffff6b44128, m=m@entry=(MOVE_NULL | unknown: 178), newSt=..., 
    givesCheck=givesCheck@entry=false) at position.cpp:1251
#3  0x0000000000431fd3 in (anonymous namespace)::qsearch<(<unnamed>::NodeType)0u, true>(Position &, Search::Stack *, Value, Value, Depth) (pos=..., 
    ss=ss@entry=0x7ffff6b41670, alpha=alpha@entry=251, beta=beta@entry=252, depth=depth@entry=DEPTH_QS_NO_CHECKS) at search.cpp:1620
#4  0x00000000004316e3 in (anonymous namespace)::qsearch<(<unnamed>::NodeType)0u, false>(Position &, Search::Stack *, Value, Value, Depth) (pos=..., 
    ss=ss@entry=0x7ffff6b41640, alpha=alpha@entry=-252, beta=beta@entry=-251, depth=depth@entry=DEPTH_ZERO) at search.cpp:1621
#5  0x0000000000433f04 in (anonymous namespace)::search<(<unnamed>::NodeType)0u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., 
    ss=0x7ffff6b41610, alpha=alpha@entry=251, beta=beta@entry=252, depth=depth@entry=ONE_PLY, cutNode=<optimized out>) at search.cpp:885
#6  0x0000000000433583 in (anonymous namespace)::search<(<unnamed>::NodeType)0u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., 
    ss=0x7ffff6b415e0, alpha=alpha@entry=-252, beta=beta@entry=-251, depth=depth@entry=2, cutNode=<optimized out>) at search.cpp:1214
#7  0x0000000000433583 in (anonymous namespace)::search<(<unnamed>::NodeType)0u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., 
    ss=ss@entry=0x7ffff6b415b0, alpha=alpha@entry=251, beta=beta@entry=252, depth=depth@entry=3, cutNode=cutNode@entry=true) at search.cpp:1214
#8  0x00000000004361bc in (anonymous namespace)::search<(<unnamed>::NodeType)1u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., 
    ss=ss@entry=0x7ffff6b41580, alpha=alpha@entry=-252, beta=-216, depth=depth@entry=4, cutNode=cutNode@entry=false) at search.cpp:1205
#9  0x0000000000436ae6 in (anonymous namespace)::search<(<unnamed>::NodeType)1u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., 
    ss=0x7ffff6b41550, alpha=alpha@entry=216, beta=beta@entry=252, depth=<optimized out>, cutNode=cutNode@entry=false) at search.cpp:1227
#10 0x0000000000438ba5 in Thread::search (this=this@entry=0x7ffff6b44010) at search.cpp:430
#11 0x000000000043b238 in MainThread::search (this=0x7ffff6b44010) at search.cpp:298
#12 0x000000000043dd71 in Thread::idle_loop (this=0x7ffff6b44010) at thread.cpp:113
#13 0x00007ffff78f0c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#14 0x00007ffff7bc16fa in start_thread (arg=0x7ffff6b43700) at pthread_create.c:333
#15 0x00007ffff7056b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by ddugovic** [comment]
Yes, your fix is efficient although it's strange that search continues after a player has lost their king.
