### ISSUE TITLE
Implement or disable NNUE for variants

### ISSUE THREAD

**Issue by ddugovic** [ddugovic/Stockfish#580]
Even if we implement this for variants, who would tune the NNUE values?

Design constraints:
* Maximum 32 pieces (30 without kings)
* Kings get a fixed ID, other pieces get ID in order of placement
* Maximum 64 squares?
* Maximum 2 "NNUE dirty pieces"?

**Comment by ddugovic** [comment]
Compatibility matrix:

https://github.com/ddugovic/Stockfish/blob/31c10018aba25deaa7f5f34ecddc73b23c705ff5/src/benchmark.cpp#L434-L469

**Comment by ddugovic** [comment]
For some variants, implementing this would be impractical and added code may slow down standard chess:
* Non-royal kings (antichess, two kings)
* PIece list contains more than 32 pieces (horde)
* Piece list is appended to (crazyhouse)
* Piece list ordering is dynamic when executing and/or undoing a move (atomic)

**Comment by ddugovic** [comment]
Compatibility matrix (I do not recall if this has changed):

https://github.com/ddugovic/Stockfish/blob/76ac430793ecea97902089bcc96bf9138a651bd9/src/benchmark.cpp#L434-L469

**Comment by sf-x** [comment]
>     * Non-royal kings (antichess, two kings)

This is indeed a problem. There's a net architecture (kp) and code for it which does not treat kings specially, 
>     * Piece list is appended to (crazyhouse)
>     * Piece list ordering is dynamic when executing and/or undoing a move (atomic)

Does not matter as long as you can do incremental update. Or simply disable incremental.
For crazyhouse, pieces in hand are a bit of a problem, as there can be multiple of a kind.

**Comment by sf-x** [comment]
> Even if we implement this for variants, who would tune the NNUE values?

This is not Leela, IIRC Sergio Vieri used 2-3 days of his 90-core to practically complete the optimization. (The rest of time is spent tweaking parameters and waiting the same 2-3 days). Consider that this will give eval which wouldn't break with every merge.
> Design constraints:
> 
>     * Maximum 32 pieces (30 without kings)

 Shogi has 36...
>     * Kings get a fixed ID, other pieces get ID in order of placement
> 
>     * Maximum 64 squares?

Similar thing is used for shogi, so no. Might need changing the trainer, I'm not sure.
>     * Maximum 2 "NNUE dirty pieces"?

This only matter for playing code and shouldn't be too difficult to change.

**Comment by ddugovic** [comment]
Thanks for this guidance.  As of a679d60 there is limited support for variants other than crazyhouse and horde (for atomic, incremental updates ignore the blast which removes pieces).

I attempted to implement horde, however when the board contains more than 32 pawns (24 white, 8 black) errors start occurring so I'll need to give the feature encoder some more thought.

**Comment by gekkehenker** [comment]
>Even if we implement this for variants, who would tune the NNUE values?

For what it's worth.

My 27/6 net (The one that convinced the Stockfish-devs to merge) was trained on just 1 billion depth 8 positions and "finetuned" with 100m depth 12 positions. 6 piece tablebase was used during generation of both datasets. (Using tablebases massively improves net training)

Creating a passable net doesn't require too much computation power. Essentially just 4 days of computation on my 12 thread was enough to crush the highly optimized and tuned for handcrafted eval that SF used.

**Comment by ddugovic** [comment]
Thanks for this information... I'll keep it in mind in case people want to start tuning weights.

With respect to crazyhouse and horde (incomplete feature transformations) one of my goals for this repository is to avoid adding code which degrades performance of standard chess, so Lichess can continue to distribute a single binary for evaluating all games (most of which are standard chess, and as https://database.lichess.org/ indicates, crazyhouse is the most popular variant).

Until the upstream repository supports >32 pieces per player and uses instructions, data structures, etc. with respect to that, I do not intend to maintain support for >32 pieces per player.
