### ISSUE TITLE
Losses on time in suicide

### ISSUE THREAD

**Issue by lantonov** [ddugovic/Stockfish#583]
The newest version tries to mate in suicide. Just before the mate (#1) it starts a long think and loses in time. Older versions (about 1 year ago) play normally suicide. One of the recent games with the new version below:
[Event "ICS unrated suicide match"]
[Site "freechess.org"]
[Date "2020.08.30"]
[Round "-"]
[White "FishtestC"]
[Black "masheen"]
[Result "0-1"]
[WhiteElo "0"]
[BlackElo "2766"]
[TimeControl "120+12"]
[Variant "suicide"]
[Annotator "6. +1000.01"]

1. e3 g5 2. Ba6 Nxa6 3. Qh5 Bg7 4. Qxh7 Bxb2 5. Qxh8 Bxa1 6. Qxg8 Kf8
{FishtestC forfeits on time} 0-1

A recent game with the old version
[Event "ICS unrated suicide match"]
[Site "freechess.org"]
[Date "2020.08.30"]
[Round "-"]
[White "masheen"]
[Black "FishtestC"]
[Result "0-1"]
[WhiteElo "2766"]
[BlackElo "0"]
[TimeControl "120+12"]
[Variant "suicide"]
[Annotator "1... +1.59"]

1. g4 g6 2. h3 c5 3. c3 h5 4. gxh5 gxh5 5. h4 Qb6 6. b4 cxb4 7. cxb4 Qxb4 8. Qc2 Qxh4 9. Qxc8 Qxf2 10. Qxb7 Qxe1 11. Qxa8 Qxc1 12. Qxb8 Qxf1 13. Qxe8 Qxg1 14. Qxf8 Qxb1 15. Qxe7 Nxe7 16. Rhxb1 Ng6 17. Re1 h4 18. a4 h3 19. d4 h2 20. Ra2 Rg8 21. Ra3 Nh4 22. Rg1 hxg1=K 23. Rg3 Rxg3 24. a5 Kf1 25. e3 Rxe3 26. d5 Ke2 27. a6 Kd3 28. d6 Re7 29. dxe7 Ng6 30. e8=K f6 31. Kxd7 Ne7 32. Kxe7 Ke4 33. Kxf6 Ke5 34. Kxe5
{FishtestC wins by having less material (stalemate)} 0-1

**Comment by ddugovic** [comment]
Duplication step:

```
./stockfish bench antichess 16 1 13 test.fen depth
```

test.fen:

```
startpos moves e2e3 g7g5 f1a6 b8a6 d1h5 f8g7 h5h7 g7b2 h7h8 b2a1 h8g8 e8f8
```

result:

```
Stockfish 2020-08-30 Multi-Variant by D. Dugovic, F. Fichter et al.
info string variant antichess startpos rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w - - 0 1

Position: 1/1
info string classical evaluation enabled
0 score mate 0
bestmove (none)
```

**Comment by ddugovic** [comment]
@lantonov Possible duplicate or #580 which I have reopened (thanks to upstream simplifications it might be possible to implement NNUE for more variants).

If you are building from current master, you may need to configure:

```
setoption name Use NNUE value false
```

**Comment by lantonov** [comment]
Indeed, this is most probably the problem. I will try this. Thanks!

**Comment by ddugovic** [comment]
Thanks.  Let me know if the issue persists and I can reopen this and investigate further.
