### ISSUE TITLE
Stockfish Misses Forced Checkmates in Atomic starting with Qe7/Qe2

### ISSUE THREAD

**Issue by sabfrompc** [ddugovic/Stockfish#586]
So for some strange reason we've only noticed this bug happening with SF when the forced mate sequence starts with Qe7+ or Qe2+, but for some mates that start with those moves and an open e-file, SF just completely ignores the possibility.
https://lichess.org/analysis/atomic/b2qk3/P7/1Pn4P/2PP1PP1/8/8/8/4K3_w_-_-_0_1
or 
https://lichess.org/analysis/atomic/3qk3/8/2n5/1B1p4/5P1p/2P4P/8/4K2R_w_-_-_0_1
After any move is made here SF immediately recognizes that it is a mate, but until a move is played it refuses to look at this move and prunes it for some reason. There have been multiple examples of this noticed going back at least a year. I thought someone else was going to report it, otherwise I would have reported it much sooner.

A non contrived example of this bug occurring would be in the position after 1. Nf3 f6 2. Nc3 Nh6 3. g4 c6 4. d4 e6 5. e4 f5 6. exf5 Bd6 7. Nd5 Bg3 8. hxg3. Here SF doesn't seem to recognize that 8... exd5 is mate, even though it does recognize that it is not black's best move. No matter how long it is given to see this short and simple mate it seemingly ignores it. It is important to note that this bug does not occur on the mobile app. This is likely because the mobile app uses an older version of SF from before 2020, as it was some time around January of 2020 that this bug was introduced.

Stockfish may rule out Qe7/Qe2 in other cases as well, which could help to explain the strange evaluations of positions like https://lichess.org/analysis/atomic/r3k1nr/ppB3pp/2n1p3/1B1p1b2/3P3q/4PP2/PP4PP/R2QK2R%20w%20KQkq%20-%203%2013 but I cannot confirm or deny that with any certainty.

**Comment by ddugovic** [comment]
Thanks, I'll merge https://github.com/official-stockfish/Stockfish/pull/3214 first while http://www.variantfishtest.org:6543/tests/view/5f9d442b6e23db221d9e93ac is still running...

**Comment by ddugovic** [comment]
Curiously this is reproducible with the queen on d8 or f8, but not on h7.

**Comment by ddugovic** [comment]
I am waiting on bugfix test results http://www.variantfishtest.org:6543/tests/view/5fa11ba36e23db221d9e93b2

**Comment by ddugovic** [comment]
Having said that, I see another possible bugfix:
http://www.variantfishtest.org:6543/tests/view/5fa1263b6e23db221d9e93b5
