### ISSUE TITLE
Any official release?

### ISSUE THREAD

**Issue by student-t** [ddugovic/Stockfish#74]
Is there an offical (or stable) release that users can download and use? What's the version used by lichess?

**Comment by ddugovic** [comment]
Thanks for your interest.  You do understand that Stockfish is [GPL-licensed](http://github.com/ddugovic/Stockfish/blob/master/Copying.txt), right?  If SmallChess bundles Stockfish, the complete SmallChess/Stockfish source code must be made available under the same license.

**Comment by student-t** [comment]
That's not the point. SmallChess won't bundle Stockfish, I have my own chess engine. I'm simply interested in the state of the project because I see you make many commits. When I checked the code, it looked like the normal Stockfish evaluation is still being used, apart from atomic chess.

**Comment by niklasf** [comment]
You can check out my fork, where I tag versions that are considered stable enough to be used by lichess: https://github.com/niklasf/Stockfish/releases.

Besides - irrelevant here - communicating with Stockfish via the UCI protocol does not mean your program has to be GPL-licensed (https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html.en#MereAggregation).

**Comment by student-t** [comment]
Thanks.
