### ISSUE TITLE
Stockfish (zh) refuse to start

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#96]
Or sometimes start after a long time ( the message "Loading engine..." stays). Tested in Chrome and FF.

here (and following moves) : https://fr.lichess.org/16ExrSfk/white#19
and here (and following moves) : https://fr.lichess.org/VZHy5KHR#25

**Comment by ianfab** [comment]
I guess this is more likely to be a problem with lichess/fishnet than with Stockfish.

**Comment by isaacl** [comment]
@Vinvin20 Unless you can reproduce in a native build, I'd suggest reporting lichess issues on [ornicar/lila](https://github.com/ornicar/lila) or if definitely a pnacl issue, [niklasf/stockfish.pexe](https://github.com/niklasf/stockfish.pexe)

**Comment by Vinvin20** [comment]
Ok Revook suggested a browser cache issue. The engine start correctly (but a bit slow) after a crtl+F5.

**Comment by niklasf** [comment]
We can track this in ornicar/lila if it reoccurs.
